pokt-network/poktroll

- docs/static/openapi.yml
- proto/pocket/supplier/tx.proto
- x/supplier/client/cli/tx.go
- x/supplier/client/cli/tx_stake_supplier.go
- x/supplier/keeper/msg_server_stake_supplier.go
- x/supplier/module_simulation.go
- x/supplier/simulation/stake_supplier.go
- x/supplier/types/codec.go
- x/supplier/types/message_stake_supplier.go
- x/supplier/types/message_stake_supplier_test.go
Ran the following command:
```
ignite scaffold message stake-supplier --module supplier --signer address --yes
```
- Added a new definition for `pocket.supplier.MsgStakeSupplierResponse` in `openapi.yml`.
- Added a new service method `StakeSupplier` and `MsgStakeSupplier` message in `tx.proto`.
- Added a new command `CmdStakeSupplier` in `tx.go`.
- Added a new file `tx_stake_supplier.go` in `cli` package.
- Added a new file `msg_server_stake_supplier.go` in `keeper` package.
- Added a new file `stake_supplier.go` in `simulation` package.
- Updated the `RegisterCodec` and `RegisterInterfaces` functions in `codec.go`.
- Added a new file `message_stake_supplier.go` in `types` package.
- Added a new file `message_stake_supplier_test.go` in …
> [Supplier] Scaffolded the StakeSupplier message and nothing else

- docs/static/openapi.yml
- proto/pocket/supplier/genesis.proto
- proto/pocket/supplier/query.proto
- proto/pocket/supplier/supplier.proto
- x/supplier/client/cli/query.go
- x/supplier/client/cli/query_supplier.go
- x/supplier/client/cli/query_supplier_test.go
- x/supplier/genesis.go
- x/supplier/genesis_test.go
- x/supplier/keeper/query_supplier.go
- x/supplier/keeper/query_supplier_test.go
- x/supplier/keeper/supplier.go
- x/supplier/keeper/supplier_test.go
- x/supplier/types/genesis.go
- x/supplier/types/genesis_test.go
- x/supplier/types/key_supplier.go
Simply ran the following command:
```
ignite scaffold map supplier --module supplier --signer address --no-message --index address --yes
```
1. The file `x/supplier/keeper/supplier_test.go` is a new file with 63 lines of code, containing test suites for the `x/supplier/keeper` package and test functions for `GetSupplier`, `RemoveSupplier`, and `GetAllSupplier` functions.
2. The file `x/supplier/types/genesis_test.go` includes changes related to a valid genesis state with two suppliers in the `SupplierList` and a testcase for duplicated suppliers in the `SupplierList`.
3. The diff includes the addition of two new test files, `query_supplier_test.go` and `list_supplier_test.go`, which contain test cases for the `ShowSupplier` and …
> [Supplier] Scaffolded the Supplier type (without CRUD messages) and nothing else

- docs/static/openapi.yml
- proto/pocket/application/tx.proto
- x/application/client/cli/tx.go
- x/application/client/cli/tx_unstake_application.go
- x/application/keeper/msg_server_unstake_application.go
- x/application/module_simulation.go
- x/application/simulation/unstake_application.go
- x/application/types/codec.go
- x/application/types/message_unstake_application.go
- x/application/types/message_unstake_application_test.go
Ran the following command
```bash
ignite scaffold message unstake-application --module application --signer address --yes
```
This pull request introduces several changes related to unstaking applications:
1. A new Go file named `unstake_application.go` is added to the repository. It contains a command `CmdUnstakeApplication()` that is used to broadcast a message to unstake an application. The command validates the message and generates or broadcasts a transaction.
2. The file `codec.go` is modified by adding a new message type `MsgUnstakeApplication` to the `RegisterCodec` and `RegisterInterfaces` functions. These changes indicate the registration of the new message type for unstaking an application.
3. A new test file named `message_unstake_application_test.go` is added to the …
> [Supplier] Scaffolded the UnstakeSupplier message and nothing else

- docs/static/openapi.yml
- go.mod
- proto/pocket/service/relay.proto
Scaffolding & adding the `Relay` type
1. In the go.mod file, the dependency `google.golang.org/genproto` has been removed from the require section.
2. In the go.mod file, the dependency `google.golang.org/genproto` has been added to the require section.
3. A new file named `relay.proto` has been added in the `proto/pocket/service` directory. This file contains protobuf message definitions related to relaying requests and responses.
4. The `relay.proto` file imports other protobuf files and defines message structures for relay requests, relay responses, and their metadata. It also includes definitions for JSON-RPC request and response payloads, REST request payloads, and REST response payloads.
Please review these changes and provide any …
> [WIP][Session] Adding the Relay type

- docs/static/openapi.yml
- go.mod
- proto/pocket/gateway/gateway.proto
- proto/pocket/gateway/genesis.proto
- proto/pocket/gateway/query.proto
- x/gateway/client/cli/query.go
- x/gateway/client/cli/query_gateway.go
- x/gateway/client/cli/query_gateway_test.go
- x/gateway/genesis.go
- x/gateway/genesis_test.go
- x/gateway/keeper/gateway.go
- x/gateway/keeper/gateway_test.go
- x/gateway/keeper/query_gateway.go
- x/gateway/keeper/query_gateway_test.go
- x/gateway/types/genesis.go
- x/gateway/types/genesis_test.go
- x/gateway/types/key_gateway.go
Ran `ignite scaffold map gateway --module gateway --signer address --no-message --index address --yes`
This pull request includes various changes to multiple files. Here is a summary of the diff:
- Changes to the file `x/gateway/gateway_test.go`:
- Added test cases to validate the `GatewayList` field in the `GenesisState` struct.
- Assertion added to verify the consistency of the `GatewayList` in the `genesisState` and `got.GatewayList`.
- Changes to the file `genesis_test.go`:
- Added new test cases to validate the genesis state for the gateway module.
- Added gateway addresses in the test cases to ensure proper validation.
- Changes to the file `query_gateway_test.go`:
- Added two new test functions to test gateway queries (single and paginated).
- The functions test various scenarios …
> [Gateway] Add the Gateway type definition

- docs/static/openapi.yml
- proto/pocket/supplier/tx.proto
- x/supplier/client/cli/tx.go
- x/supplier/client/cli/tx_create_claim.go
- x/supplier/keeper/msg_server_create_claim.go
- x/supplier/module_simulation.go
- x/supplier/simulation/create_claim.go
- x/supplier/types/codec.go
- x/supplier/types/message_create_claim.go
- x/supplier/types/message_create_claim_test.go
This message type is a nested dependency of the `Miner` via the `SupplierClient`.
- Scaffolded `MsgCreateClaim` message types, handlers, etc.:
```
ignite scaffold message create-claim session_header:SessionHeader root_hash --signer SupplierAddress --module supplier
```
(NB: generated a temporary SessionHeader duplicate in the supplier module so the above would work; subsequently, removed and updated protobuf import and usage.)
- Switch `MsgCreateClaim#root_hash` type from `string` to `[]byte`  & refactor usages.
Related to:
- #13 
- #7 
This message type is a nested dependency of the `Miner` via the `SupplierClient`.
> [Miner] chore: scaffold create-claim message

- docs/pkg/observable/README.md
- docs/template/pkg/README.md
- pkg/observable/channel/observable.go
- pkg/observable/channel/observable_test.go
- pkg/observable/channel/observer.go
- pkg/observable/interface.go
- add `Observer#IsClosed()` to prevent redundant unsubscription
- simplify `channelObservable`
- update observable pkg README
- update pkg README template
- add `Observable#Next()` conveniece method to just get the next value
1. In the file `docs/pkg/observable/README.md`, the package path has been updated from `pkg/observable` to `pocket/pkg/observable`.
2. In the file `docs/template/pkg/README.md`, the section "Architecture Diagrams" has been added to provide visual representations of the package's design and flow.
3. In the file `pkg/observable/channel/observable.go`, the `Next` method has been added to synchronously return the next value from the observable.
4. In the file `pkg/observable/channel/observable.go`, the `goPublish` …
> [Observable] chore: observable touchup

- Makefile
- go.mod
Separate `make go_develop` into `make go_develop` and `make go_develop_and_test`
This pull request separates tests from go_develop by modifying the Makefile and go.mod files. It removes the go_test command from the go_develop target and adds a new target go_develop_and_test that generates protos, mocks, and runs all tests.
N/A
> feat: seperate tests from go_develop

- pkg/observable/channel/map.go
- pkg/observable/channel/map_test.go
Adds `Map`, a function which transforms a "source" observable into a new, "destination", observable via the provided `transformFn`.
This pull request introduces the map channel observable operator. It includes the implementation of the `Map` function in the `pkg/observable/channel/map.go` file, as well as tests in the `pkg/observable/channel/map_test.go` file. The `Map` function takes an observable and applies a transform function to each notification received from the observable. If the transform function returns a `skip` boolean of true, the notification is skipped and not emitted to the resulting observable. The tests cover various scenarios of mapping bytes to palindromes and checking their validity. The patch also includes improvements to comments and test names for better …
> [Miner] feat: add the map channel observable operator

- go.mod
- x/application/keeper/msg_server_delegate_to_gateway.go
- x/application/keeper/msg_server_stake_application.go
- x/application/keeper/msg_server_undelegate_from_gateway.go
- x/application/keeper/query_application.go
- x/gateway/keeper/msg_server_stake_gateway.go
- x/gateway/keeper/msg_server_unstake_gateway.go
- x/supplier/keeper/msg_server_create_claim.go
- x/supplier/keeper/msg_server_stake_supplier.go
- x/supplier/keeper/msg_server_submit_proof.go
- x/supplier/keeper/msg_server_unstake_supplier.go
Call `ValidateBasic` on messages & txs before on-chain actors execute the business logic.
The `ValidateBasic` function is often called on the client side, but it is just as important to validate it again (for redundancy) before it is used to execute a state transition.
This pull request adds an extra layer of message validation to several files in the codebase. The patch modifies the `go.mod` file and adds validation checks to message handling functions in various modules including application, gateway, and supplier. Overall, the changes aim to improve the validation and error handling in the code.
No issue. Just a small change added for redundancy
> [Test] Enforce `msg.ValidateBasic` in all the `keepers` and `msgServers` for redundancy

- pkg/relayer/proxy/errors.go
- pkg/relayer/proxy/interface.go
- pkg/relayer/proxy/jsonrpc.go
- pkg/relayer/proxy/proxy.go
- pkg/relayer/proxy/server_builder.go
- proto/pocket/shared/supplier.proto
- The file `supplier.proto` had a deletion of an empty line at the end of the file.
- The file `errors.go` was added to the `pkg/relayer/proxy` directory. It defines a package `proxy` and imports `cosmossdk.io/errors` as `sdkerrors`. It declares a variable `codespace` as "relayer/proxy" and an error `ErrUnsupportedRPCType` with the code 1 and message "unsupported rpc type".
- The file contains interface definitions for the RelayerProxy and RelayServer. The RelayerProxy interface is responsible for starting and stopping all advertised relay servers and notifying the miner about the served relays. It also includes methods for verifying relay request signatures and sessions, as well as signing relay responses. The RelayServer interface …
> [Proxy] feat: add general proxy logic and server builder

- pkg/either/errors.go
- pkg/either/types.go
Adds the `either.AsyncError` type (i.e. `either.Either[chan error]) as well as helper methods, analogous to `either.Either`'s:
- `SyncErr(err  error) either.AsyncError`
- `AsyncErr(errCh chan error) AsyncError`
- `AsyncError#SyncOrAsyncError() (error, chan error)`
- `AsyncError#IsSyncError() bool`
- `AsyncError#IsAsyncError() bool`
This pull request includes two patches. 
The first patch adds the `either.AsyncErr` type and helper functions to the package `either`. It introduces the `SyncErr` function, which creates an `AsyncError` from a synchronous error, and the `AsyncErr` function, which creates an `AsyncError` from an error channel. It also includes functions to decompose the `AsyncError` into its components and check if it represents a synchronous or asynchronous error.
The second …
> feat: add either.AsyncErr type & helpers

- pkg/client/events_query/client.go
- pkg/client/interface.go
- pkg/either/types.go
Quick refactoring of `either.Either[[]byte]` to `either.Bytes` for improved readability & convenience.
This pull request refactors the code by adding an alias `either.Bytes`. The changes are made in the `pkg/client/events_query/client.go`, `pkg/client/interface.go`, and `pkg/either/types.go` files. The `eventsBytes` field in the `eventsBytesAndConn` struct now receives an `either.Bytes` type instead of `either.Either[[]byte]`. Similarly, the `eventsBzObservable` and `eventsBzPublishCh` variables in the `newEventsBytesAndConn` function are changed to `observable.Observable[either.Bytes]` and `channel.NewObservable[either.Bytes]()` respectively. The `eventsBzPublishCh` parameter in the `goPublishEventsBz` function is also changed to `chan<- either.Bytes`. Furthermore, in the …
> [Either] refactor: add `either.Bytes` alias

- internal/testclient/testeventsquery/client.go
- pkg/client/block/client.go
- pkg/client/block/client_test.go
Refactors a flaky block client test to eliminate flakiness (as far as measured, 0:10000) and improve readability.
> fix: flaky block client test

- proto/pocket/session/session.proto
- x/session/keeper/session_hydrator.go
- x/session/keeper/session_hydrator_test.go
This pull request adds the `session_end_block_height` field to the `SessionHeader` message in the `proto/pocket/session/session.proto` file. The `session_end_block_height` represents the height at which a session ended, which is the last block of the session. This patch also updates the `session_hydrator.go` file to set the `session_end_block_height` based on the `session_start_block_height` and `NumBlocksPerSession` values. Additionally, the `session_hydrator_test.go` file is updated to include test cases for the `session_end_block_height` field, ensuring that it is set correctly.
- #161 
> feat: Add session_end_block_height to SessionHeader

- pkg/client/block/client.go
- pkg/client/tx/client.go
- pkg/observable/channel/map.go
- pkg/observable/channel/map_test.go
Simplifies usage of `channel.Map` for consumers which need a context reference, a common case.
This pull request includes three patches:
- Patch 1/3: Refactors the `MapFn` type in the `map.go` file to receive a context argument.
- Patch 2/3: Makes improvements based on review feedback in the `map.go` file.
- Patch 3/3: Fixes usage of `MapReplay` after the refactor in the `client.go` file.
Overall, these patches aim to enhance the functionality and readability of the codebase.
Relates to:
- #13 
- #169 
- #168 
Many consumers of `channel.Map` require a context reference in their map/transform functions.
> [Off-chain] refactor: `MapFn`s receive context arg

- pkg/relayer/interface.go
- pkg/relayer/session/errors.go
- pkg/relayer/session/options.go
- pkg/relayer/session/session.go
- pkg/relayer/session/sessiontree.go
Use depinject to construct `relayerSessionsManager`.
This pull request introduces several changes. 
The first patch (1/3) adds a new file `options.go` to the `pkg/relayer/session` package, which contains a new function `WithStoresDirectory`. This function sets the path on disk where KVStore data files are created. 
The second patch (2/3) adds a small improvement to the `WithStoresDirectory` function. It changes the error message when the session tree store path already exists. 
The third patch (3/3) improves the readability of the error messages in the `errors.go` file. It updates the error codespace and the error messages to make them more descriptive. It also updates the error message when the session tree store path already exists.
Overall, these changes aim to enhance the management …
> [Sessions] chore: Use depinject for sessions mgr construction

- pkg/relayer/interface.go
- pkg/relayer/proxy/errors.go
- pkg/relayer/proxy/options.go
- pkg/relayer/proxy/proxy.go
- pkg/relayer/proxy/relay_signer.go
- pkg/relayer/proxy/relay_verifier.go
- pkg/relayer/proxy/server_builder.go
Use `depinject` and options functions to construct the `RelayerProxy`
This pull request introduces changes to the relayer package. 
The diff includes the following modifications:
- Added a new RelayerProxyOption type to configure the relayer proxy.
- Changed the error codespace from "relayer/proxy" to "relayer_proxy".
- Renamed error variables according to the new error codespace.
- Added a new file options.go that defines options for the relayer proxy.
- Added a NewRelayerProxy function to create a new relayer proxy.
- Refactored the relayerProxy struct to use the new options and validate the configuration.
- Modified the SignRelayResponse and VerifyRelayRequest methods to use the signing key name.
- Updated the error messages in the VerifyRelayRequest method.
- Added a function to …
> [Proxy] chore: Use depinject for relayerProxy

- pkg/appgateserver/cmd/cmd.go
- pkg/appgateserver/endpoint_selector.go
- pkg/appgateserver/errors.go
- pkg/appgateserver/jsonrpc.go
- pkg/appgateserver/options.go
- pkg/appgateserver/relay_verifier.go
- pkg/appgateserver/server.go
- x/service/types/relay.go
* Use `depinject` to construct the `appGateServer`.
* Attempt to simplify dependencies
* Rely on context to stop the `sppGateServer` and its dependencies
1. In the `relay.go` file:
- Three blank lines have been added.
- The SessionHeader field of Meta in the RelayRequest struct was uncommented.
- The Signature field of Meta in the RelayRequest struct was assigned a value of nil.
- An extra blank line was added at line 67.
2. In the `options.go` file:
- A new file `options.go` has been added in the `pkg/appgateserver` package. It defines two functions: `WithSigningInformation` and `WithListeningUrl`.
3. In the `errors.go` file:
- The `codespace` variable has been updated to `"appgateserver"`.
- The error variable names have been updated to …
> [AppGate] Use depinject and refactor cmd

- x/supplier/keeper/query_supplier.go
- x/supplier/keeper/query_supplier_test.go
Add context to the "key not found" error message that is returned when querying for a supplier which hasn't staked yet:
This pull request improves the error message seen by RPC consumers when the given supplier is not found on-chain. It adds a formatted message that includes the address of the supplier.
- #126 
> [Supplier] chore: improve supplier not found error message

- pkg/observable/channel/collect.go
- pkg/relayer/miner/gen/template.go
- pkg/relayer/miner/relay_fixtures_test.go
Commit mistakenly omitted changes from #191.
This pull request includes some chore improvements to #191. It adds some code to handle locking and unlocking of a mutex in the `Collect` function in `pkg/observable/channel/collect.go` file. It also updates a comment in the `template.go` file in the `pkg/relayer/miner/gen` package to reflect changes in the difficulty threshold. 
- #126 
- #191
I walked away from an ssh key passphrase prompt, mistakenly thinking that my `git push ...`  worked.
> [Miner, Testing] chore: omitted improvments to #191

- localnet/poktrolld/config/appgate_server_config.yaml
- pkg/appgateserver/cmd/cmd.go
- pkg/appgateserver/config/appgate_configs_reader.go
- pkg/appgateserver/config/appgate_configs_reader_test.go
- pkg/appgateserver/config/errors.go
- testutil/yaml/yaml.go
Replace custom configuration flags with a `--config` flag that sources config. directives from a yaml file
```yaml
self_signing: true
signing_key: app1
listening_endpoint: http://localhost:42069
query_node_url: tcp://127.0.0.1:36657
```
This pull request introduces several changes across multiple files. Here is a summary:
- A new file named "yaml.go" was added in the "testutil/yaml" directory. This file contains a function called "NormalizeYAMLIndentation", which removes extra indentation and converts tab indentation to space indentation in YAML content. This utility function ensures correct parsing by handling indentation sensitivity in YAML.
- Another new file, "appgate_server_config.yaml", was added. It includes the following changes:
- The server now signs all incoming requests with …
> [AppGate] feat: Add app gate config

- localnet/poktrolld/config/relayminer_config.yaml
- pkg/relayer/cmd/cmd.go
- pkg/relayer/config/errors.go
- pkg/relayer/config/relayminer_configs_reader.go
- pkg/relayer/config/relayminer_configs_reader_test.go
- pkg/relayer/proxy/jsonrpc.go
- pkg/relayer/proxy/proxy.go
- testutil/yaml/yaml.go
Source the RelayMiner configuration from a yaml config file instead of flags
This pull request introduces several changes across multiple files. 
In the file `proxy.go`, the type `servicesEndpointsMap` has been changed from `map[serviceId]url.URL` to `map[serviceId]*url.URL`. This means that the values in the map are now pointers to `url.URL` instead of the actual `url.URL` objects.
A new file named "errors.go" has been added to the "config" package. It defines error variables related to the RelayMiner configuration, covering cases such as unmarshaling YAML content, invalid URLs, and invalid configuration parameters.
The file `relayminer_config.yaml` has been added, containing various changes:
- `query_node_url` parameter has been added to specify the URL of a full pocket node for reading …
> [RelayMiner] feat: Add relay miner config file handling

- Makefile
- Fixes `todo_this_commit` target by completing rename of `DISCUSS_IN_THIS_COMMIT` to `TODO_DISCUSS_IN_THIS_COMMIT`.
- Removes redundant entries from `TODO_KEYWORDS`.
This pull request fixes an issue with the Makefile. It adds a new target `todo_this_commit` and removes a redundant `TODO_KEYWORDS`. The `todo_this_commit` target lists all the TODOs needed to be done in this commit. The patch also updates the `grep` command in the `todo_this_commit` target to include both `TODO_IN_THIS_COMMIT` and `TODO_DISCUSS_IN_THIS_COMMIT`.
N/A
`make todo_this_commit` doesn't behave as expected.
> [Tooling] fix: Makefile: `todo_this_commit` target & remove redundant `TODO_KEYWORDS`

- pkg/appgateserver/relay_verifier.go
- pkg/appgateserver/synchronous.go
- pkg/relayer/proxy/relay_signer.go
- pkg/relayer/proxy/relay_verifier.go
- x/service/types/relay.go
In order to normalize data signing, `RelayRequest` and `RelayResponse` `.GetSignableBytes` now returns the hash of the unmarshaled structure instead of the hash itself, avoiding hashing to occur out side of the function.
This pull request includes several changes across multiple files. 
In pkg/appgateserver/relay_verifier.go, the code has been updated to use the new API for obtaining the signable bytes of the relay response. The previous code used the crypto.Sha256 function to compute the hash of the response bytes, but it has been replaced with the correct function call supplierPubKey.VerifySignature. The function is now using the responseSignableBz variable instead of the old responseBz variable.
In pkg/appgateserver/synchronous.go, a similar change has been made. The code now uses the …
> Make Relay{Request,Response}.GetSignableBytes return the signable hash

- pkg/appgateserver/cmd/cmd.go
- pkg/deps/config/suppliers.go
- pkg/polylog/polyzero/logger.go
- pkg/relayer/cmd/cmd.go
Although unit tests were passing, I failed to double-check localnet output before merging #219. Apparently I assumed that the zero value zerolog logger (feel free to re-read carefully as many times as necessary :stuck_out_tongue_closed_eyes:) used `os.Stderr` as the output; however, it seems not to be the case. I've also ruled out level misconfiguration, it's definitely the output configuration.
This pull request contains changes to multiple files in the repository. Here is a summary of the changes:
- In `pkg/appgateserver/cmd/cmd.go`, there are some changes related to configuring the logger for the command context.
- In `pkg/deps/config/suppliers.go`, a new function `NewSupplyLoggerFromCtx` is added to supply a `polylog.Logger` instance from the given context.
- In …
> [🪲Off-chain, Polylog] fix: broken localnet output 🙄

- .github/workflows-helpers/run-e2e-test-job-template.yaml
- e2e/tests/node.go
- testutil/testclient/localnet.go
Add an ability to override an RPC endpoint for e2e tests, so they can run locally and remotely.
1. In the file `.github/workflows-helpers/run-e2e-test-job-template.yaml`, a new environment variable `SEQUENCER_RPC_ENDPOINT` is added with the value `${NAMESPACE}-sequencer:36657`.
2. In the file `e2e/tests/node.go`, the HTTP method option is changed from `POST` to `-X POST`.
3. In the file `testutil/testclient/localnet.go`, a new import statement for `fmt` and `os` is added. Additionally, the default values for `CometLocalTCPURL` and `CometLocalWebsocketURL` are modified based on the value of the `SEQUENCER_RPC_ENDPOINT` environment variable.
Please review these changes.
> [CI/E2E] e2e fixes for e2e fixes

- .github/pull_request_template.md
That it says in the title. :point_up: 
This pull request fixes a checklist item in the PR template related to running E2E tests on DevNet.
N/A
> [Tooling] fix PR template testing checklist item formatting

- Tiltfile
- pkg/client/query/codec.go
- pkg/client/query/supplierquerier.go
- pkg/deps/config/suppliers.go
- pkg/sdk/deps_builder.go
- pkg/sdk/sdk.go
Make `POKTRollSDK` have different query node URLs so it can be used outside of `cosmosclient.Context` and be imported from external codebases that do not depend on `CosmosSDK`
Have distinct query node urls:
* JSON-RPC `QueryNodeUrl`  for event subscriptions
* gRPC `QueryNodeGRPCUrl` for query client usage
This pull request includes three patches:
1. The first patch adds distinct JSON-RPC and gRPC URLs in the `Tiltfile` and updates the port forwards accordingly.
2. The second patch triggers e2e tests in the `deps_builder.go` file.
3. The third patch fixes the import groups in the `supplierquerier.go` file.
- #259 
> [SDK] feat: Have distinct JSON-RPC and gRPC urls

- .github/pull_request_template.md
One more typo in the PR template.
N/A
> [Tooling] fix: PR template typo 2

- pkg/relayer/session/session_test.go
- testutil/testrelayer/relays.go
Moves and exports `NewMinedRelay()` test helper to  a `testrelayer` package.
This pull request refactors `NewMinedRelay` to the shared `testutil` package. It moves the function from `pkg/relayer/session/session_test.go` to `testutil/testrelayer/relays.go`. This change simplifies the code structure and promotes code reuse.
- #141 
- #250 
> [Testing, Code Health] refactor: `NewMinedRelay` to shared testutil

- .github/workflows-helpers/run-e2e-test-job-template.yaml
- Makefile
- localnet/poktrolld/config/application1_stake_config.yaml
- localnet/poktrolld/config/application2_stake_config.yaml
- localnet/poktrolld/config/application3_stake_config.yaml
- x/application/client/cli/tx_stake_application.go
- x/application/client/cli/tx_stake_application_test.go
- x/application/client/config/application_configs_reader.go
- x/application/client/config/application_configs_reader_test.go
- x/application/client/config/errors.go
Add staking amount to the config file used by the application stake cmd
- In the `.github/workflows-helpers/run-e2e-test-job-template.yaml` file, the command `poktrolld tx application stake-application` was modified. The amount `1000upokt` was removed and the flag `--config=/poktroll/localnet/poktrolld/config/application1_stake_config.yaml` was added.
- In the `Makefile` file, the `app_stake` target was modified. The argument `1000upokt` was removed from the command `poktrolld --home=$(POKTROLLD_HOME) tx application stake-application 1000upokt`.
- In the `errors.go` file, the error codes `ErrApplicationConfigEmptyContent` and `ErrApplicationConfigInvalidStake` were updated.
- The `tx_stake_application.go` file in the …
> [Configs] feat: Add stake amount in the app stake config

- .github/workflows-helpers/run-e2e-test-job-template.yaml
- Makefile
- localnet/poktrolld/config/supplier1_stake_config.yaml
- localnet/poktrolld/config/supplier2_stake_config.yaml
- localnet/poktrolld/config/supplier3_stake_config.yaml
- x/supplier/client/cli/tx_stake_supplier.go
- x/supplier/client/cli/tx_stake_supplier_test.go
- x/supplier/client/config/errors.go
- x/supplier/client/config/supplier_configs_reader.go
- x/supplier/client/config/supplier_configs_reader_test.go
Add staking amount to the config file used by the supplier stake cmd.
- The file "errors.go" added a new error variable called "ErrSupplierConfigInvalidStake" to indicate an invalid stake amount in the supplier configuration.
- The file "supplier1_stake_config.yaml" has changes to the stake amount and the addition of two services with their corresponding endpoints.
- The file "tx_stake_supplier_test.go" has changes to the `TestCLI_StakeSupplier` function, updating the test cases and arguments to align with the new `config` format.
- The file "supplier_configs_reader.go" includes various changes such as adding new structs, updating the parsing and validation functions, and adding a new import.
- The Makefile has changes in the …
> [Configs] feat: Add stake amount to supplier staking config

- go.mod
- go.sum
- Dependabot caught a vulnerability in an indirect dependency and thus once fixed I released SMT v0.8.2 this PR bumps to that version
This pull request updates the smt package to version 0.8.2. It modifies the go.mod and go.sum files, bumping the smt version from 0.8.1 to 0.8.2. The changes include 3 insertions and 3 deletions.
- Fixes N/A
> [SMT] Path Bump to v0.8.2

- go.mod
- go.sum
- Adds `MerkleRoot` type to SMT repo which is an alias of `[]byte`
- Adds ability to call `.Sum()` on result of `smst.Root()` to get the sum as a `uint64`
- Can be done via `smt.MerkleRoot(rootHashAsBytes).Sum()` AFAIK
This pull request updates the SMT library to version 0.9.2. The changes include modifications in the go.mod and go.sum files, with 3 insertions and 3 deletions.
- Fixes N/A
- Enables off-chain sum retrieval from `MerkleRoot` `[]byte` alias
> feat: update SMT to v0.9.2

- docusaurus/docs/configs/supplier_staking_config.md
This pull request adds a new file called `supplier_staking_config.md` that provides configuration details for the Supplier to submit a stake transaction. The configuration includes the stake amount, services, and their respective endpoints. The document also provides examples of how to use the staking command and explains the required fields and formats for the configuration. You can find a full example of the configuration file [here](https://github.com/pokt-network/poktroll/tree/main/localnet/poktrolld/config/supplier1_stake_config.yaml).
- #274 
- #159 
> [Config, Docs] Add supplier staking config documentation

- docusaurus/docs/configs/appgate_server_config.md
- pkg/appgateserver/server.go
This pull request contains three patches:
1. The first patch adds documentation for the AppGateServer config in the `appgate_server_config.md` file. It provides details about the configuration options available, usage, and the required fields.
2. The second patch adds a main heading to the document, providing an overview of the AppGateServer config.
3. The third patch includes edits to the `appgate_server_config.md` file, improving the structure and content of the document. It adds more details and clarifications to the configuration options and provides usage instructions for starting the AppGateServer.
Overall, these patches enhance the documentation for the AppGateServer config, making it more comprehensive and informative.
- #274 
- #159 
> [Docs] Add AppGateServer config documentation

- docusaurus/docs/configs/app_staking_config.md
This pull request adds documentation for the application staking configuration. It includes information on how to use and configure the staking settings, such as the stake amount and service IDs. Additionally, there are edits made to improve the clarity and accuracy of the documentation. Overall, this patch enhances the understanding and usage of the application staking configuration.
- #274 
- #159 
> [Config, Docs] Add application staking config documentation

- Makefile
Adding some makefile helpers to streamline the usage of [act](https://github.com/nektos/act) on the team.
@h5law shared it on our discord channel and does make it easier to verify things locally.
```bash
GITHUB_TOKEN=$(gh auth token) make act_reviewdog
```
> [Tooling] Act helpers to run github workflows locally

- pkg/relayer/session/proof.go
- pkg/relayer/session/session.go
A bad error check on session claim led to claiming sessions that were already marked as claimed. Resulting in multiple claim and proof submissions attempts. Which resulted in `session tree proof path mismatch` errors.
This pull request fixes a bad error check for session claiming. The patch modifies the `proof.go` and `session.go` files. In `proof.go`, the patch adds an import statement and modifies the `waitForEarliestSubmitProofHeight` function to correctly calculate `submitProofWindowStartHeight`. In `session.go`, the patch updates the error check in the `mapBlockToSessionsToClaim` function.
> fix: bad error check for session claiming

- e2e/tests/session.feature
- go.mod
- x/session/keeper/keeper.go
- x/session/keeper/query_get_session.go
- x/session/keeper/query_get_session_test.go
- x/session/keeper/session_hydrator.go
- x/session/keeper/session_hydrator_test.go
Fix off-by-one block height causing `session mismatch` errors during relaying.
- #366 
> [Session] fix: session mismatch due to off-by-one block height

- docusaurus/docs/quickstart.md
Remove `session-mismatch` workaround section in the `quickstart` documentation page.
This workaround is no longer needed as per #326  
> [Docs] Remove session-mismatch error workaround

- e2e/tests/session.feature
- e2e/tests/session_steps_test.go
Waiting for a claim to be submitted is subject to gov. params, and e2e tests leveraging timing to wait for transactions to be submitted make them coupled to these params and potentially flaky due to CPU load.
This PR makes `session.feature` e2e test switching from: Waiting for a number of seconds then check for tx submission to: Subscribing to target transactions and waiting until they are effectively submitted and observed on-chain.
With this change, we should no longer see these failures:
> [Test] Replace time waiting with message submission waiting

- pkg/relayer/proxy/relay_verifier.go
- pkg/relayer/proxy/synchronous.go
- x/service/types/params.go
- x/session/keeper/session_hydrator.go
As per https://github.com/pokt-network/poktroll/issues/347#issuecomment-1910838720 some sed magic to make a few adjustments.
```
:%s/sdkerrors\(\.Wrap[f?](\)\n*\s*\(.\+\),/\2\1/ge
```
Conform to wrapping errors the same everywhere.
- N/A
> [Cleanup] Wrap errors by type not by `sdkerrors` import's `Wrapf` method.

- pkg/client/tx/client.go
Increasing default gas limit from `200000` to `1000000` to verify the proofs on TestNet.
> [Quick change] Bump default gas limit

- .github/workflows-helpers/run-e2e-test.sh
Delete stuck validator Pod during E2E test.
DevNets now use a new helm chart that provisions validators as StatefulSets. As a result, if such validator had unsuccessful deployment, it won't be upgraded to the newer version due to StatefulSet uptime guarantees. We need to kill that pod, so StatefulSet controller creates a new one with correct image.
> [CI] Delete validator pod if stuck during E2E test

- .github/workflows-helpers/run-e2e-test.sh
- pkg/client/delegation/redelegation.go
- pkg/client/tx/client.go
- pkg/client/tx/client_test.go
- testutil/testclient/testdelegation/client.go
Unmarshalling transaction results logic in the delegation client is outdated, making the `RelayMiner` to panic when listening for these events.
This PR uses `tx.UnmarshalTxResult` from `txClient` to unmarshal the transaction.
When the `RelayMiner` is running and observing `EventRedelegation`s by listening to `application` transactions, if a stake application occurs, the client tries to unmarshal it with a "pre-migration" code, causing the `RelayMiner` to panic
> [Redelegation] fix: EventRedelegation unmarshaling failure

- pkg/client/block/client.go
- pkg/client/block/client_integration_test.go
- pkg/client/block/client_test.go
- pkg/client/interface.go
- pkg/client/tx/client.go
- pkg/deps/config/suppliers.go
- pkg/relayer/proxy/relay_verifier.go
- pkg/relayer/session/claim.go
- pkg/relayer/session/proof.go
- pkg/sdk/deps_builder.go
- pkg/sdk/session.go
- testutil/testclient/testblock/client.go
Out-of-band review of #444.
- Refactor concurrency primitives; swap `#latestBlock` & its mutex for a replay observable & corresponding publish channel.
- Simplify dependency injection; `NewBlockClient()` constructor expects an `cosmostypes.CometRPC` from `deps`.
- Replace `testCometClient` with a `cosmostypes.CometRPC` mock.
- #444
> [Review] out-of-band review of #444

- docusaurus/docs/internal_infrastructure/testing/load_testing_plan_1.md
- Add a column for "time" to the service metrics tables with :question: where applicable.
- Remove :question: where measurement is not feasible at the specified resolution.
- Correlating load timing/scaling with process-level CPU metering can be used to derive sub-process CPU metrics (e.g. req./res. processing).
- #432 
- #449 
> [Docs] add time & eliminate hard-to-measure metrics

- Tiltfile
JSON logs are easier to run queries against. Let's switch to json by default (just like appgate-server and relayminer) but allow modifying the log format and log level via `localnet_config.yaml`
Related helm chart feature: https://github.com/pokt-network/helm-charts/pull/33/files
> [LocalNet] Switch validator logs to json

- pkg/client/events/websocket/dialer.go
- pkg/deps/config/suppliers.go
- pkg/sdk/deps_builder.go
- pkg/sdk/deps_builder_test.go
- pkg/sdk/urls.go
- pkg/sdk/urls_test.go
Adds TLS support to the Websocket and gRPC clients
TLS support had not yet been added to the clients in the SDK. This support is required for testnet & mainnet.
> [SDK] Client TLS Support

- Tiltfile
Allows to turn delve on and off using `localnet_config.yaml`.
The related changes to helm charts were added in [this PR](https://github.com/pokt-network/helm-charts/pull/34/files) - new functionality is optional and turned off by default, so I felt confident to merge. …
> [LocalNet] Add option to turn on/off delve

- Tiltfile
Removes `tilt-restart-wrapper` because apparently tilt also injects it when `entrypoint` argument is present. As a result we ended up having `tilt-restart-wrapper` that wraps `tilt-restart-wrapper` that wraps `poktrolld` :) 
Fixes an issue with port collision on hot reloading.
> [LocalNet] Remove tilt-restart-wrapper

- localnet/kubernetes/values-appgateserver.yaml
- localnet/kubernetes/values-gateway.yaml
- localnet/kubernetes/values-relayminer-common.yaml
- pkg/appgateserver/cmd/cmd.go
- pkg/appgateserver/server.go
- pkg/relayer/cmd/cmd.go
- pkg/relayer/relayminer.go
Pprof prevents services from starting. It was not run inside a routine and caused a lock where it shouldn't have been.
- #499
> [Bug] Fix pprof endpoint

- pkg/relayer/config/proxy_http_config_parser.go
- pkg/relayer/config/supplier_hydrator.go
- pkg/relayer/proxy/synchronous.go
Make `RelayMiner` support forwarding relay requests to `https` backends.
It infers the protocol to use from the `backend_url` schema and constructs the appropriate client.
Updates the `RelayMiner` config parser and make it accept `https` backend urls.
The `RelayMiner` is not capable of forwarding relay requests to `https` `backend_url`s, which is a quite widespread setup among node runners.
https://github.com/pokt-network/poktroll/issues/499#issuecomment-2078487122
- Optionally run `make trigger_ci` if you …
> [RelayMiner] Support https backend urls

- Makefile
- e2e/tests/init_test.go
- e2e/tests/stake_supplier.feature
E2E Tests for staking the supplier: `make test_e2e_supplier`
- #460
> [Testing] Supplier staking E2E test

- x/tokenomics/keeper/settle_pending_claims.go
- x/tokenomics/keeper/settle_session_accounting.go
- x/tokenomics/keeper/settle_session_accounting_test.go
- x/tokenomics/types/errors.go
When an app exceeds its stake, make the settlement amount its full balance.
Prevent an error to avoid consensus breaking issues.
It seems that a segfault occurs when we restart due to the -ve balance an app tries to hit.
Started with this:
And then we found this:
Which led us to discovering this: …
> [Utility] Update SessionSettlement when app goes into a negative amount

- .github/workflows-helpers/run-e2e-test-job-template.yaml
- Makefile
Gateway has been deployed on our DevNets. This PR introduces `GATEWAY_URL` environment variable in CI that points to the gateway on DevNet infrastructure.
> [CI] Add GATEWAY_URL envar for e2e tests

- Tiltfile
- config.yml
- localnet/kubernetes/values-relayminer-1.yaml
- localnet/kubernetes/values-relayminer-2.yaml
- localnet/kubernetes/values-relayminer-3.yaml
- localnet/poktrolld/config/supplier1_stake_config.yaml
- localnet/poktrolld/config/supplier2_stake_config.yaml
- localnet/poktrolld/config/supplier3_stake_config.yaml
- x/supplier/config/supplier_configs_reader.go
Adds infrastructure to run and develop against LLM on LocalNet.
- #130
> [LocalNet] Add infrastructure to run LLM inference

- Makefile
- testutil/testclient/localnet.go
- Exclude Jetbrains IDE dotfiles (`.idea/`) & reviewdog.yml from `make todo_this_commit`
- Simplify localnet testutil; remove unused/unnecessary dependency injected variables
- Add godoc comments for global test variables
Observations made while using `make todo_this_commit`. …
> [Code Health] chore: cleanup localnet testutils

- config.yml
Added the following change and comment in `config.yml`. Should be self-explanatory.
```yaml
max_validators: 1
```
> [Genesis Config] Set MaxValidators to 1

- .github/workflows/main-build.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/reviewdog.yml
- .github/workflows/run-tests.yml
- .gitignore
- .tool-versions
- Dockerfile.dev
- Dockerfile.release
- Makefile
- Tiltfile
- go.mod
Provides binaries for releases and production-ready container images.
- #495
> [CI] Release artifacts job: binaries and containers

- docusaurus/docs/operate/configs/relayminer_config.md
- docusaurus/docs/operate/configs/supplier_staking_config.md
Improve supplier staking config and relay miner config documentation w.r.t upstaking, PRC types and Supplier<->RelayMiner `signing_keyname` relationship.
The documentation was not clear enough as to
* Why upstaking is needed to update the `Supplier` provided services.
* Why it is not possible to have multiple `Supplier`s assigned to the same `RelayMiner`
* What is the purpose of having multiple `RPCType`s per `Service` provided
> [Documentation] Improve RelayMiner staking related documentation

- pkg/crypto/rings/client.go
This PR fixes the `RelayRequest` signature verification process that fails when `delegateeGatewayAddresses` ordering differs at on-chain verification time.
The `RelayRequest` verification step checks that the ring addresses used to sign the request are contained within the expected ring at proof verification time. For this we use `ringSig.Ring().Equal(expectedRing)`.
The actual implementation of `Equal` [1] imposes that the request ring pubkeys must be in the **same order** as the expected one.
Using `Equal` in the following `(requestRingAddrs, expectedRingAddrs)` examples would yield undesired results in some cases:
```
* Equals(AB, ABC) == true  // desired
* Equals(BC, ABC) == false // undesired
* Equals(AC, ABC) == false // undesired
```
Given our delegation and undelegation use cases …
> [Bug] Ring address ordering makes valid subsets beings rejected

- Dockerfile.release
I ran into an issue when working with new container images on amd64 platform - `poktrolld` wasn't working. When I manually built an image with `gcompact` I was able to deploy the node. Let's include this in the next release.
Replicated an issue and fixed by manually building an image on amd64 virtual machine.
> [Quickfix] Add gcompact to container images

- Makefile
Adds a makefile target to run parameter update E2E test, as per #517.
- #517 
> [Code Health] test: add makefile target for E2E param update tests

- load-testing/config/load_test_manifest_reader.go
- load-testing/loadtest_manifest.yaml
- load-testing/localnet_loadtest_manifest.yaml
- load-testing/tests/relays_stress_helpers_test.go
- load-testing/tests/relays_stress_test.go
This change allows to run the load test against TestNet the same way we run it against LocalNet.
> [LoadTest] Switch funding account to key name instead of address

- Makefile
Makefile target to send relays to the grove gateway has been updated to use HTTP headers.
The grove gateway changed how the protocol is specified. Previously it was part of the JSON-RPC payload, it is now specified in an HTTP header.
Makefile target update. …
> [Tooling] Updated Makefile target for Grove gateway

- pkg/client/interface.go
- pkg/client/query/sharedquerier.go
- pkg/relayer/proxy/proxy.go
- pkg/relayer/proxy/relay_verifier.go
- pkg/relayer/session/claim.go
- pkg/relayer/session/proof.go
- pkg/relayer/session/session.go
- pkg/relayer/session/session_test.go
- testutil/testclient/testqueryclients/sharedquerier.go
- x/proof/keeper/msg_server_submit_proof.go
- x/proof/types/shared_query_client.go
- x/shared/session.go
- Refactor relayminer to use `proof_window_open_offset_blocks` to determine when to submit proofs.
- Add `#GetSessionGracePeriodEndHeight()` and `#GetProofWindowOpenHeight()` to `client.SharedQueryClient`.
- Refactor `shared.GetSessionGracePeriodEndHeight()` to receive `sharedParams` in preparation for making `GracePeriodBlocks` a shared param.
- #516 
- If …
> [Relayminer] refactor: relayminer to use `proof_window_open_offset_blocks`

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Adds simple support for VSC Containers or Github Codespaces.
Open project in dev container using VSCode/Codespaces and run:
```sh
make go_develop_and_test
```
> [Dev Tools] Add .devcontainer support

- e2e/tests/init_test.go
- e2e/tests/relay.feature
Add `AModuleMessageIsSubmittedBy` step to the `relay.feature` that waits for its corresponding `ClaimSettled` event to be broadcasted before moving to the next test.
Because `relay.feature` did not wait for its corresponding `ClaimSettled` event to be boradcasted, and due to the newly introduced C&P submission timings, the `session.feature` had it's initial claim count altered by the previous step.
This PR fixes this by adding the appropriate event waiting that makes `session.feature` start with a clean state.
- **THIS IS VERY …
> [E2E] Make relay feature to wait for the ClaimSettled event

- load-testing/tests/relays_stress_helpers_test.go
- load-testing/tests/relays_stress_test.go
Add missing `BlockQueryClient` dependency required by `SharedClient` to the load test.
`SharedClient` was updated to have a `BlockQueryClient` dependency which was not supplied in the load test suite.
> [LoadTest] Add missing block query client to load test

- localnet/grafana-dashboards/stress-test-dashboard.json
- telemetry/event_counters.go
- x/session/keeper/session_hydrator.go
- x/tokenomics/keeper/update_relay_mining_difficulty.go
- x/tokenomics/keeper/update_relay_mining_difficulty_test.go
- x/tokenomics/module/abci.go
Add `RelayMiningDifficulty` and `Relays EMA` metrics to `UpdateRelayMiningDifficulty` keeper function and create the corresponding Grafana charts to the stress test dashboard
A `TargetNumRelays` of `2` was used for the chart below.
- #626  …
> [Tokenomics] Update telemetry to include relay mining difficulty and EMA

- docusaurus/docs/operate/infrastructure/_category_.json
- docusaurus/docs/operate/networks/_category_.json
- docusaurus/docs/operate/quickstart/_category_.json
- docusaurus/docs/operate/quickstart/docker_compose_debian_cheatsheet.md
- docusaurus/docs/operate/quickstart/docker_compose_walkthrough.md
- docusaurus/docs/operate/run_a_node/_category_.json
- docusaurus/docs/operate/testing/_category_.json
- docusaurus/docs/operate/user_guide/_category_.json
Make it easier to onboard users to Shannon by providing a nicer skin on the docs in [poktroll-docker-compose-example](https://github.com/pokt-network/poktroll-docker-compose-example)
Also:
- Improve ToC
- Improve introduction
- Add a results video
> [Docs] Move over docs from poktroll-docker-compose-example

- docusaurus/docs/develop/developer_guide/adding_params.md
The team at ignite responded to our feature request but it's not available yet: https://github.com/ignite/cli/issues/3684.
We should update to it at some point.
> Update `adding_params.md` to use `ignite`

- Makefile
- go.mod
- tools/scripts/protocheck/cmd/codes.go
- tools/scripts/protocheck/cmd/root.go
- tools/scripts/protocheck/cmd/unstable.go
Add `protocheck` CLI tool and `unstable` subcommand to resolve stable serialization issue related to map protobuf message fields:
`go run ./tools/scripts/protocheck/cmd unstable -h`:
```
Recursively list or fix all protobuf files which omit the 'stable_marshaler_all' option.
Usage:
protocheck unstable [flags]
Flags:
-f, --fix    If present, protocheck will add the 'gogoproto.stable_marshaler_all' option to files which were discovered to be unstable.
-h, --help   help for unstable
Global Flags:
-p, --file-pattern string   Set the pattern passed to filepath.Match(), used to include file names which match. (default "*.proto")
-r, --root string           Set the path of the directory from which to start walking the filesystem tree in search of files matching --file-pattern. (default …
```
> [Tooling] Add `protocheck` CLI tool

- .github/pull_request_template.md
- api/poktroll/application/types.pulsar.go
- docusaurus/docs/explore/roadmap.md
- docusaurus/docs/explore/rpc.md
- docusaurus/docs/explore/tools.md
- docusaurus/yarn.lock
- x/application/types/types.pb.go
- x/tokenomics/types/tx.pb.go
- Updated compiled protobufs
- Links to the Shannon TestNet RPC Nodes
- Mention `consensus-breaking` in the PR template
- Related to #791
> [Docs] Minor doc updates across the board

- Tiltfile
Enable the `rest` service by default in Tilt
Since the `rest` service is used in E2E tests, it should be enabled by default to avoid non-edited `localnet_config.yaml` files to succeed E2E tests.
> [Tilt] Enable rest service by default in Tilt

- cmd/poktrolld/cmd/config.go
- go.mod
- go.sum
* Update `ShannonSDK` dependency.
* Fix `InitSDKConfig` already being sealed by `ShannonSDK`
> [SDK] Update shannon sdk dependency

- docusaurus/docs/operate/quickstart/docker_compose_debian_cheatsheet.md
- docusaurus/docs/operate/quickstart/docker_compose_walkthrough.md
Update the docs to also stake a gateway so we can use it with PATH.
> [GATEWAY POC] A couple helpers to help deploy a PATH gateway

- docusaurus/docs/develop/developer_guide/debug_tips.md
Added a debugging tip to the documentation on using transaction hashes to get more details when a transaction does not seem to have taken effect, e.g. when staking a new service returns a transaction (TX) hash but the service does not appear after a few blocks.
Debugging the process of adding a new service can be simplified using the debugging tip being added in this PR.
> [Docs] Add a debugging tip: using transaction hashes

- Makefile
- x/shared/types/params.go
- Adds the following make targets:
- `query_tx`
- `query_tx_json`
- `query_tx_log`
- `params_get_tokenomics`
- `params_get_proof`
- `params_get_shared`
- `params_get_service`
- Fixes the following make targets:
- `supplier1_unstake`
- `supplier2_unstake`
- `supplier3_unstake`
- Observations while working on #799
> [Tooling] fix and add makefile targets

- Dockerfile.release
Changes the base image from alpine to debian.
Potentially unblocks `heighliner`. 
Removes the need for `gcompat` - `glibc` compatibility layer for `musl`.
Executed build targets, built image, checked `poktrolld`.
Steps to reproduce:
```
make proto_regen
make cosmovisor_cross_compile
make ignite_release
make ignite_release_extract_binaries
docker build --no-cache --progress=plain --platform linux/amd64,linux/arm64 -t poktrolldebian -f Dockerfile.release .
docker run -it --rm --entrypoint poktrolld poktrolldebian
```
> [Container image] Change base image for release

- makefiles/params.mk
- tools/scripts/params/shared_compute_units_to_tokens_multiplier.json
Groups the param related make targets in params.mk by module and fills in gaps.
- N/A
> [Tooling] chore: re-organize params.mk targets

- x/tokenomics/keeper/token_logic_modules.go
This PR handles the case where non zero claimed rewards produce zero GMR rewards when the claimed rewards are too low.
When claimed rewards are too low, they might produce a global mint reward that is non-zero but less that 1. Since the TLM does not exepect a zero value, this might lead to a chain halt like below.
```
ERR error processing token logic modules for claim "af85b9dd2d49f1d5b133347eac2b65e7cd7a1a555fea742adba778f711207c6b": TLM "TLMGlobalMint": mint amount cannot be zero: failed to process TLM [/go/pkg/mod/cosmossdk.io/errors@v1.0.1/errors.go:155] module=server num_claim_compute_units=2 num_relays_in_session_tree=2 proof_requirement=NOT_REQUIRED session_id=af85b9dd2d49f1d5b133347eac2b65e7cd7a1a555fea742adba778f711207c6b …
```
> [Tokenomics] Prevent GMR to produce zero values

- docusaurus/docs/operate/configs/supplier_staking_config.md
- localnet/poktrolld/config/supplier1_stake_config.yaml
- localnet/poktrolld/config/supplier_stake_config_example.yaml
The existing docs for setting `rev_share_percentage` resulted in this error: `"cannot unmarshal !!seq into map[string]float32"`
> [Docs] Fix example of how to set rev share precentage

- tests/integration/service/relay_mining_difficulty_test.go
- testutil/events/filter.go
- x/application/keeper/msg_server_transfer_application_test.go
- x/proof/keeper/msg_server_create_claim_test.go
- x/proof/keeper/msg_server_submit_proof_test.go
- x/service/keeper/update_relay_mining_difficulty_test.go
- x/tokenomics/keeper/keeper_settle_pending_claims_test.go
- x/tokenomics/keeper/token_logic_modules_test.go
Remove unnecessary message type URL argument from `testutilevents.FilterEvents()`.
N/A
> [Code Health] refactor: simplify `testevents.FilterEvents()`

- Dockerfile.release
- docusaurus/docs/operate/quickstart/docker_compose_debian_cheatsheet.md
- docusaurus/docs/operate/quickstart/docker_compose_walkthrough.md
Now that we also have cosmovisor on docker-compose set-up, we need to delete different poktroll versions it downloads - in case of re-genesis. We also need to supply ca-certificates on our images.
> [Docs] Docker-compose guide: also cleanup cosmovisor history

- cmd/poktrolld/cmd/config.go
- cmd/poktrolld/cmd/root.go
- config.yml
- makefiles/todos.mk
- pkg/appgateserver/config/appgate_configs_reader.go
- pkg/relayer/session/session_test.go
- pkg/relayer/session/sessiontree.go
- proto/poktroll/application/types.proto
- proto/poktroll/service/relay_mining_difficulty.proto
- proto/poktroll/service/tx.proto
- proto/poktroll/shared/service.proto
- x/proof/keeper/msg_server_submit_proof.go
- x/session/keeper/session_hydrator.go
- x/supplier/keeper/msg_server_stake_supplier.go
- x/tokenomics/keeper/settle_pending_claims.go
- x/tokenomics/keeper/token_logic_modules.go
- x/tokenomics/keeper/token_logic_modules_test.go
- Secondary review of all `TODO_BETA` in the codebase
- Update `TODO_BETA` to only reflect things that are actual blockers
NA
> [TODOs] Update #2 to `TODO_BETA` to only reflect ACTUAL blockers

- pkg/client/query/servicequerier.go
- x/proof/keeper/msg_server_submit_proof.go
- x/proof/keeper/proof_validation.go
- x/service/keeper/query_relay_mining_difficulty.go
- x/service/keeper/query_relay_mining_difficulty_test.go
- x/service/keeper/relay_mining_difficulty.go
- x/service/keeper/relay_mining_difficulty_test.go
- x/service/types/errors.go
Make `servicekeeper.GetRelayMinerDifficulty` always return a valid difficulty by defaulting to the base difficulty for new `Services`.
Querying for a `RelayMiningDifficulty` corresponding to a new `Service` does not return a valid one.
This results in redundant code that aims to recreate the base `RelayMiningDifficulty`.
> [Service] Return the default RelayMinerDifficuly for services that have none.

- x/proof/keeper/msg_server_create_claim.go
- x/proof/keeper/msg_server_create_claim_test.go
- x/proof/keeper/msg_server_submit_proof.go
- x/proof/keeper/msg_server_submit_proof_test.go
This PR populates `NumEstimatedComputeUnits` and `ClaimedUpokt` to the following events:
* `EventClaimCreated`
* `EventClaimUpdated`
* `EventProofSubmitted`
* `EventProofUpdated`
TODO_BETA
> [C&P] Populate NumEstimatedComputeUnits and ClaimedUpokt of Claim and Proof events

- docusaurus/docs/operate/user_guide/install.md
Updating the following page for details on how to install the `poktrolld` CLI using homebrew: https://dev.poktroll.com/operate/user_guide/install
> [Docs] Update documentation on installing the `poktrolld` CLI

- docusaurus/docs/develop/developer_guide/adding_params.md
```diff
func (k msgServer) UpdateParam(ctx context.Context, msg *examplemodtypes.MsgUpdateParam) (*examplemodtypes.MsgUpdateParamResponse, error) {
// ...
if k.GetAuthority() != msg.Authority {
return nil, status.Error(
-			codes.InvalidArgument,
+			codes.PermissionDenied,
examplemodtypes.ErrExamplemodInvalidSigner.Wrapf(
"invalid authority; expected %s, got %s",
k.GetAuthority(), msg.Authority,
).Error(),
)
}
// ...
}
```
- N/A
> [Docs] adding params - fix gRPC status error code

- x/gateway/keeper/msg_server_stake_gateway.go
- x/gateway/keeper/msg_server_unstake_gateway.go
- x/gateway/keeper/msg_server_unstake_gateway_test.go
- x/gateway/keeper/msg_update_params.go
- x/gateway/keeper/query_gateway.go
Ensure all gateway message and query handlers return gRPC status errors.
- #954 
> [Code Health] fix: gateway module gRPC status error returns

- x/proof/keeper/msg_server_create_claim.go
- x/proof/keeper/msg_update_params.go
- x/proof/keeper/query_claim.go
- x/proof/keeper/query_proof.go
Ensure all proof module message and query handlers return gRPC status errors.
- #954 
> [Code Health] fix: proof module gRPC status error returns

- x/service/keeper/msg_server_add_service.go
- x/service/keeper/msg_update_params.go
- x/service/keeper/query_relay_mining_difficulty.go
- x/service/keeper/query_service.go
Ensure all service module message and query handlers return gRPC status errors.
- #860 
> [Code Health] fix: service module gRPC status error returns

- x/proof/keeper/session.go
- x/session/keeper/msg_update_params.go
- x/session/keeper/query_get_session.go
Ensure all session message and query handlers return gRPC status errors.
- #860 
> [Code Health] fix: session module gRPC status return errors

- x/shared/keeper/msg_update_params.go
Ensure all shared message and query handlers return gRPC status errors.
- #860 
> [Code Health] fix: shared module gRPC return errors

- x/application/keeper/msg_server_delegate_to_gateway.go
- x/application/keeper/msg_server_delegate_to_gateway_test.go
- x/application/keeper/msg_server_undelegate_from_gateway.go
- x/application/keeper/msg_server_undelegate_from_gateway_test.go
- x/application/keeper/msg_server_unstake_application.go
- x/application/keeper/msg_server_unstake_application_test.go
- x/application/keeper/msg_server_update_param.go
- x/application/keeper/msg_update_params.go
- x/application/keeper/query_application.go
Ensure all application message and query handlers return gRPC status errors.
- #860 
> [Code Health] fix: application module gRPC status error returns

- x/tokenomics/keeper/msg_server_update_param.go
- x/tokenomics/keeper/msg_update_params.go
Ensure all supplier message and query handlers return gRPC status errors.
- #860
> [Code Health] fix: tokenomics module gRPC return errors

- Tiltfile
Add a top-level `hot-reloading` boolean field to `localnet_config.yaml` in order to support easier disabling hot-reload.
There are times where hot-reloading is not desireable. In these instances, in the absence of such a config option, it takes 6 button clicks in the UI to accomplish the same result.
- #N/A
> chore: add localnet_config option to disable hot-reloading

- localnet/poktrolld/config/application1_stake_config.yaml
- localnet/poktrolld/config/application2_stake_config.yaml
- localnet/poktrolld/config/application3_stake_config.yaml
- localnet/poktrolld/config/gateway1_stake_config.yaml
- localnet/poktrolld/config/gateway2_stake_config.yaml
- localnet/poktrolld/config/gateway3_stake_config.yaml
- makefiles/suppliers.mk
1. The supplier unstaking make targets are missing `-y` which bypass the tx confirmation prompt
2. The application stake configs used by the application staking make targets are out of date and invalid; they may only contain one service and require a stake amount above the minimun.
3. The gateway stake configs used by the gateway staking make targets are out of date and invalid; they require a stake amount above the minimun.
- #N/A
> [Bug, Tooling] fix: app/gateway/supplier stake/unstake make targets

- tests/integration/application/application_transfer_test.go
- testutil/integration/suites/application.go
- testutil/integration/suites/gateway.go
Remove problematic build constraint from app transfer test and dependencies.
A `//go:build integration` constraint was unintentionally left in a few files related to app transfer module-integration tests, causing them to be skipped in CI. As a result, they've fallen out of date.
- #N/A
> [Bug, Testing] fix: app transfer module-integration test

- docusaurus/docs/operate/run_a_node/full_node_walkthrough.md
Update the full node walkthrough to show how to export port `26656`
- #981
> [Docs] How do I access my CometBFT endpoint externally?

- e2e/tests/node.go
Update the E2E step definition which queries the gateway. The path was `/v1`, and is now `/v1/` to avoid a redirect response. 
E2E tests involving relays fail on `main`.
Previously, `POST`ing to the `/v1` path returned a response directly; it now seems to redirect to `/v1/` which curl can't reliably handle on all platforms.
> fix: E2E tests - RPC URL path

- .github/workflows-helpers/run-e2e-test-job-template.yaml
- config.yml
- pkg/client/tx/context.go
This pull request includes changes to support larger proof transactions by increasing the maximum allowed sizes for RPC and mempool, and by adjusting the gRPC client configuration.
`RelayMiner`s simulate and broadcast transaction with multiple proofs that tend to be too large than the default gRPC client's `MaxCall{Send,Recv}MsgSize`.
> [RelayMiner] Allow big transactions simulation

- .github/workflows/label-actions.yml
- .github/workflows/main-build.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/run-tests.yml
- .github/workflows/upload-pages-artifact.yml
Upgrade github ations from `v3` to `v4`.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.com/buildwithgrove/path/actions/runs/12935368023/job/36078630477
> [Workflows] Update GitHub actions from v3 to v4

- x/tokenomics/keeper/settle_pending_claims.go
Construct a new logger instance for each session during settlement to avoid field duplication.
- https://discord.com/channels/824324475256438814/1316109400917934201/1330007345882988665
> [Off-chain] fix: duplicate log fields

- e2e/tests/node.go
- e2e/tests/reset_params_test.go
fix some function names in comment
- #{ISSUE_NUMBER}
> chore: fix some function names in comment

- x/proof/types/params.go
Reducing `MinProofSubmissionFee`.
Changes:
- Reducing `1000000` to `100`
- Description: Beta TestNet tests indicated that we require too large of a submission fee. Tried to lower the fee, but this value prevented the param change.
- Issue: https://www.notion.so/buildwithgrove/Load-Testing-Findings-15aa36edfff68020a324d1b0d490dec4?pvs=4
> [Tokenomics] Reduce MinProofSubmissionFee

- .github/workflows/release-artifacts.yml
We accidentally bumped the action version in #1041. Need to reverse to build artifacts for the release.
> [CI][Quick change] downgrade docker/login-action version

- cmd/poktrolld/cmd/root.go
- docusaurus/docs/tools/user_guide/poktrolld_cli.md
- Update `poktrolld` CLI description and documentation structure
- Update CLI description to clarify `poktrolld` as a comprehensive interface for Pocket Network interactions
- Add detailed `Long` description with link to documentation at `dev.poktroll.com`
- Fix indentation in documentation table of contents
- Enhance Homebrew troubleshooting section with improved formatting and descriptive info box
> [Docs] Followup on making homebrew troubleshooting easier to identify

- docusaurus/docs/tools/tools/shannon_alpha.md
- docusaurus/docs/tools/tools/shannon_beta.md
Replaced outdated POKTScan links with Soothe's updated counterparts for both Shannon Alpha and Beta documentation. This ensures users are directed to the correct tools and information.
Changes:
- Update Beta Explorer page
- Update Alpha Explorer page 
- Description: Alpha and Beta explorer page was out of date.
> Update links to Soothe's Explorer and GraphQL Playground

- e2e/tests/node.go
- load-testing/tests/relays_stress_helpers_test.go
- makefiles/relay.mk
I observed E2E test(s) failing on main (`make test_e2e_tokenomics`):
```
Error Trace:    /home/bwhite/Projects/pokt/poktroll/e2e/tests/init_test.go:492
/home/bwhite/Projects/pokt/poktroll/e2e/tests/session_steps_test.go:232
/home/bwhite/Projects/pokt/poktroll/e2e/tests/session_steps_test.go:163
/home/bwhite/.pkgx/go.dev/v1.23.0/src/reflect/value.go:581
/home/bwhite/.pkgx/go.dev/v1.23.0/src/reflect/value.go:365
/home/bwhite/go/pkg/mod/github.com/regen-network/gocuke@v1.1.0/run_step.go:103
/home/bwhite/go/pkg/mod/github.com/regen-network/gocuke@v1.1.0/run_scenario.go:121
/home/bwhite/go/pkg/mod/github.com/regen-network/gocuke@v1.1.0/run_scenario.go:70
/home/bwhite/go/pkg/mod/github.com/regen-network/gocuke@v1.1.0/run_doc.go:34
Error:          Expected nil, but got: map[string]interface …
```
> [Bug] fix: E2E test `s/X-App-Address/App-Address/`

- app/upgrades.go
- app/upgrades/v0.0.13.go
- docusaurus/docs/operate/upgrades/upgrade_procedure.md
Introduces `v0.0.13` upgrade handler with migration module and parameter updates.
- Adds `v0.0.13` upgrade handler with parameter updates and migrations support
- Integrates morse `migration` module KVStore into the upgrade process
- Updates `GatewayUnbondingPeriodSessions` parameter to default value
> [Upgrade] TestNet v0.0.13 upgrade

- pkg/relayer/proxy/server_builder.go
< One line summary>
Since Go 1.21, the functions in x/exp used here can already be replaced by functions from the standard library.
Changes:
- < Change 1 >
- < Change 2 > 
- Description: < Description > 
- Issue: #{ISSUE_NUMBER}
> refactor: replace golang.org/x/exp with stdlib

- testutil/integration/app.go
- testutil/keeper/migration.go
- testutil/keeper/tokenomics.go
- x/migration/keeper/keeper.go
- x/migration/module/module.go
- x/migration/types/expected_keepers.go
Remove unused gateway keeper from the migration module.
- Issue: #1034
> [Migration Module] refactor: remove unused gateway keeper dependency

- docusaurus/docs/operate/cheat_sheets/_category_.json
- docusaurus/docs/operate/cheat_sheets/docker_compose_debian_cheatsheet.md
- docusaurus/docs/operate/cheat_sheets/full_node_cheatsheet.md
- docusaurus/docs/operate/cheat_sheets/gateway_cheatsheet.md
- docusaurus/docs/operate/cheat_sheets/service_cheatsheet.md
- docusaurus/docs/operate/cheat_sheets/supplier_cheatsheet.md
- docusaurus/docs/operate/cheat_sheets/validator_cheatsheet.md
- docusaurus/docs/operate/walkthroughs/_category_.json
- docusaurus/docs/operate/walkthroughs/docker_compose_walkthrough.md
- docusaurus/docs/operate/walkthroughs/full_node_docker.md
- docusaurus/docs/operate/walkthroughs/full_node_walkthrough.md
- docusaurus/docs/operate/walkthroughs/gateway_walkthrough.md
- docusaurus/docs/operate/walkthroughs/supplier_walkthrough.md
- docusaurus/docs/operate/walkthroughs/validator_walkthrough.md
As more people look at the docs, I want to be clear & navigate them to the appropriate location:
- **Intermediate vs Advanced**: I'm trying to scare of people from going to the advanced section unless they're ready for it 
- **Time allocated**: I understand this is wrong, and we'll update it in the future, but trying to get something in the door to attract users to the right place
- **Deprecated notice**: I know docker compose is not deprecated yet, but I only want people "in the know" to keep using it for now
> [Docs] Update titles for guides and deployments with approximate time & deprecation

- .github/workflows/release-artifacts.yml
- **Tag-based builds**: Triggered automatically when a version tag (`v*..`) is pushed, producing versioned production images
- **Main branch builds**: Triggered automatically on pushes to the main branch, creating `main-prod` tagged images
- **Manual builds**: Triggered on-demand via `workflow_dispatch` with optional custom tag support
- **Platform support**: All build options generate images for both `linux/amd64` and `linux/arm64` architectures
- **Consistent image format**: All builds use the production-ready `Dockerfile.release` configuration
> [Container image] Enhance Docker Image Build Pipeline with Multiple Trigger Options

- x/tokenomics/keeper/keeper_settle_pending_claims_test.go
- x/tokenomics/keeper/settle_pending_claims.go
Fix duplicate unbonding of slashed suppliers by adding condition to check if already unbonding
- Add condition to check if supplier `IsUnbonding()` before initiating the unbonding process
- Ensure suppliers with multiple invalid claims are only unbonded once
- Unbond the supplier at the end height of the current session
- Update  test `TestSettlePendingClaims_ClaimExpired_SupplierUnstaked` to verify the fix
- Test confirms supplier stake reduction, unbonding status, slashing events and single unbonding event emission
> [Tokenomics] Duplicate unbonding of slashed suppliers

- .markdownlint.json
- docusaurus/docs/operate/cheat_sheets/full_node_cheatsheet.md
Adds a video walkthrough for the Fullnode cheatsheet
> [DOCS] Add a video walkthrough for the Fullnode Cheatsheet

- Tiltfile
Add support for local grove helm-charts repo in Tilt localnet (equivalent to the other helm chart repo).
Update your `localnet_config.yaml` to include the following section (the default, `enabled: false` will be generated on first run otherwise):
```
grove_helm_chart_local_repo:
enabled: true
path: ../grove-helm-charts
```
Changes:
- Update the default localnet_config.yaml
- Add a conditional branch to overwrite the `grove_chart_prefix` if `grove_helm_chart_local_repo.enabled` is true.
N/A
> [Tooling] chore: add support for local grove helm-charts repo in Tilt localnet

- tests/integration/migration/morse_claim_supplier_test.go
- x/supplier/module/module.go
Call `BeginBlocker` execution in `Supplier` module's `BeginBlock` handler
> [Bug] Fix missing supplier begin blocker

- docusaurus/docs/operate/cheat_sheets/gateway_cheatsheet.md
Changes the Gateway cheatsheet docs to stake for `anvil` (shannon) and not `F00C` (morse).
Noted from support discussion on Discord:
https://discord.com/channels/824324475256438814/1349394368758284330/1354376338605215877
> fix: update gateway cheatsheet to stake anvil not F00C

- makefiles/localnet.mk
- makefiles/tests.mk
- makefiles/warnings.mk
Add warning messages about Grove Helm charts setup requirement to relevant makefiles
- Add `warn_message_grove_helm_charts` target with instructions for cloning Grove Helm charts
- Update `localnet_regenesis` target to include the Grove Helm charts warning
- Update `test_e2e_env` target to include the Grove Helm charts warning
> [LocalNet] Add Grove Helm charts dependency warning to localnet and test setup

- pkg/client/interface.go
- pkg/client/supplier/client.go
- pkg/client/tx/client.go
- pkg/client/tx/client_integration_test.go
- pkg/client/tx/client_test.go
- testutil/testclient/testtx/client.go
Restores support for using `TxClient#SignAndBroadcast()` to consumers who don't know/have a specific timeout height in mind; e.g. Morse claim CLI.
- Issue: #1034
> [Morse -> Shannon Migration] chore: restore default timeout height offset support in `TxClient`

- docusaurus/docs/develop/developer_guide/debug_tips.md
- docusaurus/docs/operate/configs/relayminer_config.md
- docusaurus/docs/tools/tools/shannon_beta.md
Changing the URL to the correct one.
Reported here: https://discord.com/channels/553741558869131266/1234943674903953529/1358927454621925448
> [Quick PR] change beta rpc url in the docs

- x/migration/module/cmd/claim_morse_account.go
- x/migration/module/cmd/claim_morse_application.go
- x/migration/module/cmd/claim_morse_supplier.go
- x/migration/module/cmd/morse_keys.go
- x/shared/types/codec.go
Some tweaks to support migration module operations in the C and python client bindings.
Changes:
- Register `SupplierServiceConfig` with interface registry
- Export `LoadMorsePrivateKey`
N/A
> [Code Health] refactor: exports & interface registration

- docusaurus/docs/develop/developer_guide/walkthrough.md
- makefiles/checks.mk
PR solving 
https://github.com/pokt-network/poktroll/issues/1206
(copied below)
During make localnet_up the local cluster is expected to be named kind-kind, if this is not true, the process fails.
The documentation is not clear that after doing make localnet_up the network will be ready to send relays.
Cluster Name: Cluster naming should not be mandatory for all devs. Localnet should be deployed in any cluster name.
Localnet readiness: Despite the general health of the localnet and that it is producing blocks, there is mandatory step: make acc_initialize_pubkeys. This is required regardless you are following the full guide or just need parts of it running.
- Remove kind-kind cluster name requirement
- Add note stating that make acc_initialize_pubkeys is mandatory for relaying near the …
> [Loclanet] Remove cluster name checks - Add notes on network realy readiness

- app/upgrades/types.go
Adding `NetworkAuthzGranteeAddress` to `app/upgrades/types` to be used in other upgrades.
> [Upgrades] Adding `NetworkAuthzGranteeAddress`

- .gitignore
- Dockerfile.release
- Makefile
- makefiles/checks.mk
- makefiles/release.mk
Refactor release process by moving release helpers to dedicated makefile
- Move release functionality from main `Makefile` to new `makefiles/release.mk`
- Fix path for binary extraction from `release/*.tar.gz` to `pocket/*.tar.gz`
- Add `.secrets` to `.gitignore` for secure GitHub token management
- Improve CI/CD workflow with dedicated check and test targets
- Add reference link to Heighliner project in `Dockerfile.release`
- Simplify `check_act` implementation with clearer error messages
- Add configuration variables and documentation to release makefile
> [Workflows] Fix release-artifacts workflow

- x/session/keeper/session_hydrator.go
- x/session/keeper/session_hydrator_test.go
Reduces the amount of data transferred over the network when sending sessions by omitting service configs that are non-relevant to the requested session.
* Optimize session data size by keeping only relevant `ServiceConfig` for the session's service ID
* Add `getSupplierSessionServiceConfigIdx` helper function to locate the specific service config
* Set `ServiceConfigHistory` to nil to further reduce data size
* Update tests to verify that suppliers now only contain the specific service config
> [Session] Performance optimization for supplier service data in session hydration

- tools/scripts/upgrades/upgrade_tx_v0.1.3_alpha.json
- tools/scripts/upgrades/upgrade_tx_v0.1.3_beta.json
- tools/scripts/upgrades/upgrade_tx_v0.1.3_local.json
- tools/scripts/upgrades/upgrade_tx_v0.1.3_main.json
Upgrade transactions for v0.1.3
Release: https://github.com/pokt-network/poktroll/releases/tag/v0.1.3
```bash
./tools/scripts/upgrades/prepare_upgrade_tx.sh v0.1.3
```
> [Upgrade] `v0.1.3` transactions

- tools/scripts/upgrades/upgrade_tx_v0.1.2_beta.json
- tools/scripts/upgrades/upgrade_tx_v0.1.2_local.json
- tools/scripts/upgrades/upgrade_tx_v0.1.2_main.json
- Update `v0.1.2` authority transactions
- Update beta upgrade height
```
export TX_HASH=E94F714B017D372FC73EF8477DBE104A3083772AD9912D7A53E198C5C1B78ADF
export RPC_ENDPOINT=https://shannon-testnet-grove-rpc.beta.poktroll.com
pocketd query tx --type=hash ${TX_HASH} --node ${RPC_ENDPOINT}
```
> [Upgrade] Update `v0.1.2` transactions

- go.mod
- go.sum
Bump Shannon-SDK dependency to the latest commit as of the time of opening this PR: https://github.com/pokt-network/shannon-sdk/commit/efd370a75d51df047aab5bf8aeb717cd0598e34a
Changes:
- Update go.mod and go.sum with the new shannon-sdk SHA.
- Description: Stay up to date with the Shannon-sdk repo.
- Issue: #{ISSUE_NUMBER}
> Bump shannon-sdk dependency: SHA efd370a75d51

- docusaurus/docs/operate/upgrades/2_release_procedure.md
- tools/scripts/upgrades/upgrade_tx_v0.1.5_alpha.json
- tools/scripts/upgrades/upgrade_tx_v0.1.5_beta.json
- tools/scripts/upgrades/upgrade_tx_v0.1.5_local.json
- tools/scripts/upgrades/upgrade_tx_v0.1.5_main.json
Create upgrade transactions for the `v0.1.5` upgrade using the following:
"./tools/scripts/upgrades/prepare_upgrade_tx.sh v0.1.5"
Minor documentation improvements
> [Upgrade] Transactions for v0.1.5

- x/migration/keeper/msg_server_claim_morse_account.go
- x/migration/keeper/msg_server_claim_morse_application.go
- x/migration/keeper/msg_server_claim_morse_supplier.go
- x/migration/module/autocli.go
Cleaning up done and/or simple TODOs.
Changes:
- Remove done TODOs.
- Update the Morse claim message handlers' conditional re-application of the waived Morse claim tx fee to consider whether fee waiving is enabled.
N/A
> [Code Health] chore: cleanup TODOs

- app/upgrades.go
- app/upgrades/v0.1.6.go
This PR adds the v0.1.6 upgrade, which aims to reduce the memory footprint of the Supplier config history pruning which always marshals and saves all Suppliers.
* Added a new upgrade handler for v0.1.6
* Added the v0.1.6 upgrade to the allUpgrades list
> [Upgrade] v0.1.6 upgrade handler to reduce memory footprint for Supplier config pruning

- tools/scripts/upgrades/upgrade_tx_v0.1.7_alpha.json
- tools/scripts/upgrades/upgrade_tx_v0.1.7_beta.json
- tools/scripts/upgrades/upgrade_tx_v0.1.7_local.json
- tools/scripts/upgrades/upgrade_tx_v0.1.7_main.json
Add upgrade transactions JSON for v0.1.7.
- #1236 
> [Upgrade Transactions] chore: add v0.1.7 upgrade transactions JSON

- tools/scripts/upgrades/upgrade_tx_v0.1.9_alpha.json
- tools/scripts/upgrades/upgrade_tx_v0.1.9_beta.json
- tools/scripts/upgrades/upgrade_tx_v0.1.9_local.json
- tools/scripts/upgrades/upgrade_tx_v0.1.9_main.json
Create upgrade transactions for the v0.1.9 upgrade using the following:
"./tools/scripts/upgrades/prepare_upgrade_tx.sh v0.1.9"
> chore: Add upgrade v0.1.9 tx json files

- app/upgrades.go
- app/upgrades/v0.1.10.go
- x/tokenomics/keeper/settle_pending_claims_context.go
- x/tokenomics/keeper/settle_pending_claims_test.go
Ensure supplier service configurations for claim serviceIds are properly cached in the settlement context
Primary Changes:
- Add `cacheSupplierServiceConfig` function to hydrate supplier with service config when missing
- Update `cacheSupplier` to ensure cached suppliers include service configurations for all claims
- Use `slices` package to efficiently search for existing service configurations
Secondary changes:
- Import standard library `slices` package
- Add a test that ensures that claim settlement succeeds when a supplier is involved in multiple claims of different services.
Chain halt with the following error:
```
could not settle pending claims due to error TLM "TLMRelayBurnEqualsMint": queueing operation: distributing rewards to supplier with operator address …
```
> [Bug] Fix supplier service configuration caching in claim settlement process

- tools/scripts/upgrades/upgrade_tx_v0.1.10_alpha.json
- tools/scripts/upgrades/upgrade_tx_v0.1.10_beta.json
- tools/scripts/upgrades/upgrade_tx_v0.1.10_local.json
- tools/scripts/upgrades/upgrade_tx_v0.1.10_main.json
- tools/scripts/upgrades/upgrade_tx_v0.1.9_beta.json
* Update `v0.1.9` upgrade transaction to new reorg height (5 blocks after snapshot's height 7881)
* Add `v0.1.10` Upgrade transactions
> [Bug] Fix update v0.1.9 tx upgrade height, add v0.1.10 transactions

- app/upgrades.go
- app/upgrades/v0.1.11.go
- docusaurus/docs/operate/morse_migration/4_state_transfer_playbook.md
Prepares v0.1.11 onchain network upgrade for application.
- Add authz grant for `MsgRecoverMorseAccount`
- Add `allow_morse_import_override` migration module param
- Set it to `true` for Alpha and Beta TestNets
- #1294 
> [Morse -> Shannon Migration] chore: prepare v0.1.11 upgrade for submission

- docusaurus/docs/2_explore/4_morse_migration/4_state_transfer_playbook.md
Update `--node` and `--grpc-addr` flags for step 6 in the state migration playbook.
- #1294 
> [Docs] Update migration docs flags

- docusaurus/docs/2_explore/4_morse_migration/4_state_transfer_playbook.md
Fix a typo in the migration docs, state transfer playbook. `MORSE_STATE_EXPORT` was renamed to `MORSE_MAINNET_STATE_EXPORT` but one reference didn't get updated.
- N/A
> [Docs] fix: migration state transfer playbook - bash variable name

- docusaurus/docs/1_operate/4_faq/7_custodians_faq.md
Verbiage and link changes to Custodians FAQ
> Verbiage and link changes to Custodians FAQ (May 19, 2025)

- pkg/encoding/hex.go
- testutil/sample/sample.go
- x/migration/keeper/morse_claimable_account.go
- x/migration/keeper/query_morse_claimable_account.go
- x/migration/keeper/query_morse_claimable_account_test.go
- x/migration/types/message_claim_morse_account.go
- x/migration/types/message_claim_morse_application.go
- x/migration/types/message_claim_morse_supplier.go
Normalize all Morse hex addresses usages to upper case so that different cases of the same string are treated as the same address.
- #1343
> [Tooling] fix: normalize all Morse hex address cases to uppercase

- tools/installer/full-node.sh
- tools/scripts/upgrades/prepare_upgrade_tx.sh
Update installer scripts to handle upgrade height skipping and modify release checksum behavior.
- Add support for downloading and applying `--unsafe-skip-upgrades` flags in the full-node.sh installer
- Configure the node systemd service to use the downloaded skip upgrade heights
- Modify the upgrade tx preparation script to make checksums optional for all networks
- Add URL constant for skip upgrade heights file location
- Update comments to reflect changes in checksum behavior
- Add detailed logging during the skip upgrades configuration process
> [Ops] Add support for skipping upgrade heights in node installer scripts

- cmd/flags/flags.go
- x/migration/module/cmd/claim_morse_account.go
- x/migration/module/cmd/claim_morse_account_bulk.go
- x/migration/module/cmd/claim_morse_supplier.go
- x/migration/module/cmd/claim_morse_supplier_bulk.go
- x/migration/module/cmd/flags.go
- x/migration/module/cmd/types.go
- x/migration/types/query.pb.go
Refactor Morse migration CLI commands with improved flag handling, documentation, and code organization
- Remove unused short flag constants and variables from `flags.go`
- Consolidate flag variables into new `cmd/flags.go` file with shared constants
- Update CLI command descriptions and examples for better clarity and consistency
- Refactor bulk claim commands with improved parameter validation and error handling
- Move account type definitions (`MorseAccountInfo`, `ShannonAccountInfo`) to shared `types.go`
- Remove duplicate flag variable declarations across command files
- Add comprehensive YAML template examples in command documentation
- Improve function naming and documentation comments throughout
- Add validation for template file parameters (owner, operator, stake amount should …
> [CLI][Review] Review of #1378

- docusaurus/docs/1_operate/1_cheat_sheets/1_service_cheatsheet.md
- x/service/keeper/msg_server_add_service.go
- x/service/keeper/msg_server_add_service_test.go
- x/service/types/params.go
- x/shared/types/service.go
Allow `AddService` keeper handler to update the `ComputeUnitsPerRealy` of an existing `Service` by the `ServiceOwner`
- Issue: #1368 
> [Service] Allow AddService handler to update CUPR

- tools/scripts/params/gov_params.sh
This pull request change the `tools/scripts/params/gov_params.sh` file. It removes the `./` prefix from the `pocketd` command in multiple functions to simplify command execution.
> [Tooling] Fix pocketd path on gov params script

- x/migration/recovery/recovery_allowlist.go
**Why**: Simplify the process of migrating multisigs from Morse to Shannon.
**Changes**: Add multisig addresses to the recovery allowlist.
**Context**:  https://github.com/pokt-network/poktroll/pull/1318
**Next Steps**: 
1. Create a native [Shannon multisig](https://github.com/cosmos/cosmos-multisig-ui)
2. Recover Morse multisig as a shannon multisig
3. QED
> [Migration] Multisig Address Recovery Make sure we can recovr the wpokt multisig address

- pkg/client/supplier/client.go
This pull request adds null checks for `txResponse` in logging statements within the `SubmitProofs` and `CreateClaims` methods of `pkg/client/supplier/client.go`.
These changes ensure that logging operations are only performed when `txResponse` is not nil, improving the robustness of the code.
> [Bug] Nil txResponse on Supplier client

- app/upgrades.go
- app/upgrades/v0.1.14.go
- app/upgrades/vNEXT.go
Onchain upgrade to v0.1.14.
- N/A
> chore: bump onchain version to v0.1.14

- cmd/rpc.go
Ensure that `--network` flag usage only modifies flags which are registered on the current command.
- N/A
> [Tooling] fix: network flag

- x/migration/module/cmd/claim_morse_supplier_bulk.go
Update file paths and key mapping logic in the Morse supplier migration command
- Fix variable reference
- Fix wrong owner address assignation
- CLI drop error file not found
- CLI drop error about wrong owner address format
> [CLI] Fix claim morse suppliers bulk command

- app/upgrades.go
- app/upgrades/v0.1.16.go
- app/upgrades/vNEXT.go
- app/upgrades/vNEXT_Template.go
Prepare v0.1.16 onchain upgrade. 
- #1421
> [Upgrade] chore: prepare v0.1.16 onchain upgrade

- tools/scripts/params/bulk_params_main/shared_params.json
Temporarily reducing the unbonding period from 21 days to 7 days for nodes affected during the migration. We will revert this change on June 26th 2025.
- Reduce `supplier_unbonding_period_sessions` from `6048` -> `2016`
> [SUPPLIER][PARAMS] Reducing supplier unbonding from 21 days to 7 days

- x/migration/keeper/msg_server_claim_morse_supplier.go
> [!IMPORTANT]
> This is potentially a critical vulnerability
Currently, if both of the following are true:
1. A Supplier started unstaking BEFORE state shift 
2. The Supplier FINISHED unbonding AFTER state shift at the time of claim
Then, for NON-CUSTODIAL nodes, the the staked assets go to the `operator` INSTEAD of the `owner.`
https://discord.com/channels/553741558869131266/1336462284645601280/1382205197480231093
In `x/migration/keeper/msg_server_claim_morse_supplier.go`, we have this code snippet:
```go
// Mint the Morse node/supplier's stake to the shannonSigningAddress account balance.
// The Supplier stake is subsequently escrowed from the shannonSigningAddress account balance
// UNLESS it has already unbonded during the migration.
// NOTE: The supplier module's staking fee …
```
> [Supplier] Bug when Claiming Morse Supplier that's fully unstaked

- pkg/client/tx/client.go
- pkg/client/tx/errors.go
Enhance transaction timeout error handling with better validation, error messages, and logging.
- Add validation to check if transactions are actually successful before reporting timeout errors
- Improve error reporting by including transaction height in timeout error messages
- Add warning log when a transaction expected to timeout is actually successful
- Add TODOs for future refactoring of transaction error handling architecture
- Add considerations about simplifying error handling by leveraging SDK's built-in errors
> [RelayMiner] Fix Transaction Timeout Error Handling

- app/upgrades.go
- app/upgrades/v0.1.19.go
Prepare onchain upgrade to `v0.1.19`
- PR: #1464
> [Upgrade] Prepare v0.1.19 upgrade

- .github/workflows/release-artifacts.yml
Now that the issue with GitHub Action is fixed (https://github.com/softprops/action-gh-release/issues/628 and https://github.com/softprops/action-gh-release/issues/627), we can go back to using version instead of gitsha.
Basically reverts #1458 and pins to the latest (at the moment) version.
> [CI] pin action-gh-release version to v2.3.2

- x/migration/module/cmd/claim_morse_account_bulk.go
- x/migration/module/cmd/claim_morse_supplier_bulk.go
- x/migration/module/cmd/types.go
Add advanced customization flags and keyring improvements for supplier migration.
- Introduced new flags (`--add-operator-share`, `--name-prefix-pattern`, `--use-index-names`) for enhanced supplier migration configuration.
- Improved keyring integration to support dynamic key naming during migrations.
- Fixed YAML stake config handling for operator rewards and rev share allocation adjustments.
- Updated JSON serialization for accounts to include keyring name support.
> [CLI] Add advanced customization flags for bulk commands.

- x/migration/module/cmd/claim_morse_account_bulk.go
- x/migration/module/cmd/claim_morse_supplier_bulk.go
Update Morse bulk claim logic to handle non-custodial node cases and skip already-claimed accounts.
- `claim-suppliers` was not allowing to claim when the output address was a node
- `claim-accounts` was exiting earlier when an account was a node.
> Update Morse bulk to handle output address node and skip already claimed accounts.

- pkg/client/events/replay_client.go
- pkg/client/tx/client.go
- pkg/client/tx/client_test.go
- pkg/client/tx/context.go
- pkg/relayer/session/claim.go
- pkg/relayer/session/persistence.go
- pkg/relayer/session/proof.go
- pkg/relayer/session/session.go
- pkg/relayer/session/session_persistence_test.go
- pkg/relayer/session/sessiontree.go
- x/shared/types/session.go
Enhance relayer session management with non-leaking context handling and session cleanup mechanisms
- Fix context propagation in client packages to use passed context instead of creating new ones
- Refactor `deleteExpiredSessionTreesFn` to properly handle session tree cleanup
- Add periodic cleanup of expired session trees based on proof window close height
- Extract common session tree deletion logic into a dedicated `deleteSessionTrees` function
- Improve logging messages for better debugging and traceability
- Replace direct logger usage with session-specific logger in session tree operations
> [RelayMiner] Improve Context Handling and Session Tree Management in Relayer

- app/upgrades.go
- app/upgrades/v0.1.21.go
- app/upgrades/vNEXT.go
- app/upgrades/vNEXT_Template.go
v0.1.21 - upgrade to:
- Update the Morse account recovery allowlist with exchange allowlist updates and invalid addresses
- Slim down excessively sized proof module events:
Refs:
- https://dev.poktroll.com/develop/upgrades/release_procedure
> [Upgrade] Adding v0.1.21.go upgrade handler

- pkg/relayer/session/session.go
Fix session deletion bug by retrieving SMT root before closing the KVStore
- Move `sessionSMT` creation before the `sessionTree.Delete()` call
- Ensure SMT root is retrieved while the KVStore is still open
- Add comments explaining the importance of the execution order
<details>
<summary>`panic: d.nx != 0` (Click for full stack trace)</summary>
```
relayminer  | panic: d.nx != 0
relayminer  |
relayminer  | goroutine 9751 [running]:
relayminer  | crypto/internal/fips140/sha256.(*Digest).checkSum(0xc0069b7418)
relayminer  | /opt/hostedtoolcache/go/1.24.3/x64/src/crypto/internal/fips140/sha256/sha256.go:214 +0x194
relayminer  | crypto/internal/fips140/sha256.(*Digest).Sum(0xc00c418f80, {0x0, 0x0, 0x0})
relayminer  | /opt/hostedtoolcache/go/1.24.3/x64/src/crypto/internal/fips140/sha256/sha256. …
```
> [RelayMiner][Bug] Create sessionSMT before tree deletion to ensure proper SMT root retrieval

- tools/rc_helpers/suppliers.sh
Adds 
Some background
- `$(pocket query tx --query ...)` Queries “inputs” to block processing
- `$(pocket query block-results --query ...)` Queries “outputs” of block processing
- Events may be emitted during the input phase OR the output phase
- There is no single query to process both in full detail
```bash
$ source tools/rc_helpers/suppliers.sh
Run the following --help messages to get more information about the commands
shannon_query_unique_claim_suppliers_addresses --help
shannon_query_supplier_tx_events --help
shannon_query_supplier_block_events --help
```
```bash
shannon_query_unique_claim_suppliers_addresses 143286 144286 main
[
...
"pokt1yalpttxw8qe0j6mzyn87g6zktce2tt684v0s64",
...
]
```
```bash
$ shannon_query_supplier_tx_events 143286 144286 …
```
> [Helpers] `pocketd` helpers in `.rc` format for supplier debugging

- Dockerfile.release
- go.mod
- pkg/polylog/polyzero/logger.go
- pkg/polylog/polyzero/options.go
- pkg/relayer/cmd/cmd_relay.go
- pkg/relayer/proxy/http_utils.go
- pkg/relayer/proxy/relay_builders.go
- pkg/relayer/proxy/sync.go
Fix memory issues that was spiking due to the usage of `io.ReadAll` base on `pprof` reports of `heap`
- Introduce Go GC tuning defaults in Dockerfile for production memory optimization.
- Refactor request body handling to use pooled buffers and size limits for improved memory management.
- Centralize body closing logic in `CloseRequestBody` to enhance consistency and error handling.
- Replace `io.ReadAll` with `SafeReadBody` for capped, streamlined payload reads.
- Add `SerializeHTTPResponse` implementation for deterministic response serialization.
- Enable timestamping in logger initialization for improved log tracing.
- High Memory usage on load (actively receiving relays)
> [RM] Handle `io.ReadAll` memory issue.

- cmd/faucet/serve.go
- cmd/signals/exit.go
- e2e/tests/init_test.go
- go.mod
- load-testing/tests/relays_stress_test.go
- pkg/client/events/query_client.go
- pkg/client/events/query_client_test.go
- pkg/client/events/replay_client.go
- pkg/client/events/replay_client_integration_test.go
- pkg/client/events/websocket/state.go
- pkg/relayer/cmd/cmd_start.go
- pkg/relayer/session/claim.go
- pkg/relayer/session/session_test.go
- testutil/testclient/testblock/client.go
Improve signal handling with graceful shutdowns and enhance event subscription resilience with connection state tracking.
- Enhanced `GoOnExitSignal` with graceful shutdown support, timeout handling, and multiple signal trapping
- Refactored `EventsQueryClient` to improve connection management and resource cleanup
- Added connection state tracking to `EventsReplayClient` with improved logging for debugging
- Updated logging with emoji indicators for better visual distinction between message types
- Fixed resource leaks by ensuring proper cleanup of websocket connections
- Updated caller code to use the new `GoOnExitSignal` signature
> [RelayMiner] Enhance Signal Handling and Event Subscription Reliability

- tools/scripts/params/bulk_params_beta/staking_params.json
- tools/scripts/params/bulk_params_main/staking_params.json
Increase validator pool on Beta and Mainnet from 5 -> 6
- Mainnet `staking.max_validators` from 5 -> 6
- Beta TestNet `staking.max_validators` from 5 -> 6
> [BETA][MAINNET][VALIDATORS][STAKING] Increase validator pool on Beta and Mainnet from 5 -> 6

- app/upgrades.go
- app/upgrades/v0.1.24.go
Add upgrade handler for v0.1.24 release
- Add `v0.1.24.go` upgrade handler file with upgrade logic
- Register `Upgrade_0_1_24` in `allUpgrades` slice for upgrade execution
- Include upgrade comments documenting the changes in this release
> [Upgrade] Add v0.1.24 upgrade handler

- app/upgrades.go
- app/upgrades/v0.1.26.go
Prepare upgrade plan for v0.1.26 with backward compatible relay response signature verification
- Add `Upgrade_0_1_26` handler in `app/upgrades/v0.1.26.go`
- Update upgrade registry to include v0.1.26 upgrade
Protocol upgrade to enable smooth transitions with backward compatible relay response signature verification
> upgrade: Prepare upgrade plan for v0.1.26

- pkg/relayer/proxy/http_server.go
- pkg/relayer/proxy/relay_meter.go
- pkg/relayer/relayminer.go
- pkg/relayer/session/session.go
- testutil/testrelayer/relays.go
- testutil/testtree/tree.go
Fixing RelayMiner log panic reported by the community:
- **Root Cause**: Multiple goroutines tried to use the same logger.
- **Solution**: Create context-specific loggers.
Side change: fixing some broken tests on main.
> [RelayMiner] Avoid concurrent access to shared logger

- app/app.go
- app/upgrades/vNEXT.go
- config.yml
> [Review] Review of #1262: `[IBC] Prepare pocket for IBC connectivity`

- go.mod
- go.sum
Update the dependency version for `github.com/pokt-network/smt` in the `go.mod` file. The version has been upgraded from `v0.13.0` to `v0.14.1`.
> [RelayMiner] Bump SMT version

- go.mod
- go.sum
_tl;dr Workaround to prevent slow EndBlockers from blocking RPC queries_
Temporarily use Pocket's fork of CometBFT as a hacky workaround related to mutexes.
Ref: https://github.com/pokt-network/cometbft/pull/2
Next steps: https://github.com/pokt-network/cometbft/issues/3
> [CometBFT] Use Pocket's fork temporarily

- docusaurus/docs/3_protocol/actors/4_path_gateway.md
Update PATH Gateway configuration documentation link to point to operate section
- Updated PATH Gateway configuration link from `https://path.grove.city/configs/config_intro` to `https://path.grove.city/operate`
- N/A
- N/A
> [Docs] fix path config link

- docusaurus/docs/1_operate/3_configs/4_relayminer_config.md
- docusaurus/docs/1_operate/3_configs/5_websocket_support.md
- docusaurus/docs/4_develop/developer_guide/walkthrough.md
- localnet/kubernetes/values-relayminer-common.yaml
- localnet/pocketd/config/relayminer_config_full_example.yaml
- makefiles/release.mk
- pkg/relayer/cmd/cmd_start.go
- pkg/relayer/config/config.schema.yaml
- pkg/relayer/interface.go
- pkg/relayer/session/persistence.go
- pkg/relayer/session/session.go
- pkg/relayer/session/session_persistence_test.go
- pkg/relayer/session/session_storage_mode_test.go
- pkg/relayer/session/sessiontree.go
_tldr Fix: RelayMiner claims creation without proof submission in Pebble in-memory mode_
---
- RelayMiner WAS creating claims
- RelayMiner WAS NOT submitting proof
- This resulted in lost rewards
- **Storage lifecycle mismatch**: Pebble in-memory mode required calling `Stop()` to flush data for claims, but this destroyed the store needed for subsequent proof generation.
- **SimpleMap** didn't have this issue since it doesn't require explicit lifecycle management.
- `:memory:` - Uses SimpleMap (pure Go map, recommended)
- `:memory_pebble: `- Uses Pebble with in-memory VFS (experimental)
- `SimpleMap`: Keep data in memory throughout the lifecycle
- `Pebble in-memory`: Preserve session metadata after Stop() for proof generation
- `Disk storage`: Restore data from disk as needed (unchanged)
- …
> [RelayMiner] Ensure `in-memory` RelayMiner still submits proofs

- cmd/rpc.go
Fix a bug causing the --network flag to be ineffective.
- N/A
> fix: --network flag not working
