.github/workflows/go.yml
Installs ignite, builds pocketd (3m30s), and runs tests (2m30s).
=> Create first CI job

Makefile, docs/static/openapi.yml, go.mod, proto/pocket/gateway/tx.proto, testutil/keeper/gateway.go, x/gateway/client/cli/tx_stake_gateway.go, x/gateway/client/cli/tx_stake_gateway_test.go, x/gateway/client/cli/tx_unstake_gateway.go, x/gateway/client/cli/tx_unstake_gateway_test.go, x/gateway/genesis.go, x/gateway/keeper/msg_server_unstake_gateway.go, x/gateway/keeper/msg_server_unstake_gateway_test.go, x/gateway/types/errors.go, x/gateway/types/expected_keepers.go, x/gateway/types/genesis.go, x/gateway/types/message_stake_gateway_test.go, x/gateway/types/message_unstake_gateway.go, x/gateway/types/message_unstake_gateway_test.go
- Update message verification
- Update test coverage
- Implement the UnstakeGateway keeper method
- Add unit tests for the CLI and message handler
Fixes #19 
=> [Gateway] Implement UnstakeGateway message and add Tests

docs/static/openapi.yml, go.mod, proto/pocket/session/query.proto, x/application/types/genesis.go, x/session/client/cli/query.go, x/session/client/cli/query_get_session.go, x/session/keeper/query_get_session.go
Just ran the following command:
```
ignite scaffold query get-session --module session --yes
```
This pull request adds a new query command "get-session" to the session module. It also adds the necessary files and code to handle this query.
- #15
=> [Session] Scaffold the GetSession query

docs/static/openapi.yml, proto/pocket/application/tx.proto, x/application/client/cli/tx.go, x/application/client/cli/tx_delegate_to_gateway.go, x/application/keeper/msg_server_delegate_to_gateway.go, x/application/module_simulation.go, x/application/simulation/delegate_to_gateway.go, x/application/types/codec.go, x/application/types/message_delegate_to_gateway.go, x/application/types/message_delegate_to_gateway_test.go
Ran `ignite scaffold message delegate-to-gateway --module application --signer address --yes`
This pull request includes various changes across multiple files:
1. A new file `msg_server_delegate_to_gateway.go` was added to the `x/application/keeper` package. It defines a method called `DelegateToGateway` in the `msgServer` type that handles the `MsgDelegateToGateway` message from the application module.
2. A new file `tx_delegate_to_gateway.go` was added to the `x/application/client/cli` directory. It contains a command called `CmdDelegateToGateway`, which is used to broadcast a message called `delegate-to-gateway` using the Cosmos SDK client package.
3. A new test file `message_delegate_to_gateway_test.go` was added to the `types` package. It includes a test function …
=> [AppGate] Scaffold delegate-to-gateway message

.github/workflows/reviewdog.yml, e2e/tests/node.go, pkg/observable/channel/observable.go, pkg/observable/channel/observer.go, pkg/relayer/proxy/proxy.go, x/application/types/message_delegate_to_gateway.go, x/application/types/message_stake_application.go, x/application/types/message_undelegate_from_gateway.go, x/application/types/message_unstake_application.go, x/gateway/types/message_stake_gateway.go, x/gateway/types/message_unstake_gateway.go, x/supplier/types/message_create_claim.go, x/supplier/types/message_stake_supplier.go, x/supplier/types/message_submit_proof.go, x/supplier/types/message_unstake_supplier.go
Ran
``` 
find . -type f -name "*.go" -exec sed -i '' 's/var _ \(.*\) = &\(.*\){}/var _ \1 = (*\2)(nil)/g' {} +
```
This pull request includes several changes:
- Added a new job called "check_non_standard_interface_implementations" in the `.github/workflows/reviewdog.yml` file. This job checks for non-standard interface implementation statements and reports an error if found.
- Updated the buffer size of a observable's publish channel in the `pkg/observable/channel/observable.go` file.
- Updated the implementation check for `pocketdBin` struct in the `e2e/tests/node.go` file.
- Updated the implementation check for `channelObservable` struct in the `pkg/observable/channel/observable.go` file.
- Updated the implementation check for `channelObserver` struct in the …
=> chore: conform to golang standard of interface implementation registration

Makefile, tools/scripts/itest.sh
In the context of discovering and fixing flaky tests:
Adds a bash script and makefile target which runs go tests using the `-count` flag (according to the `go_test_count` positional arg) in a loop `loop_limit` (positional arg) number of times.
Tweaking the `go_test_count` and `loop_limit` for a given `package_path` will result in different durations between output from test batches. These values can be tuned to find an interval which is reasonable to distinguish between unresponsiveness but still sufficiently exercising the test suite to expose flakiness.
This pull request adds a new script and Makefile target called "itest" for running tests iteratively. The new script "itest.sh" takes three arguments: the number of tests to run, the loop limit, and the package path. It runs the …
=> [Testing] test: add itest script and makefile target

go.mod, testutil/application/mocks/mocks.go, testutil/gateway/mocks/mocks.go, testutil/supplier/mocks/mocks.go, x/application/client/cli/helpers_test.go
This pull request replaces the `mocks.go` files with `.gitkeep` files in the `testutil` directory. It also updates the `go.mod` file to include the `github.com/cosmos/cosmos-proto` dependency.
=> [Code Health] Replace `mocks.go` w/ `.gitkeep`

go.mod, pkg/client/events_query/client_test.go
=> [Test] Temporarily skip a flaky test `TestEventsQueryClient_Subscribe_Succeeds`

config.yml, docs/static/openapi.yml, go.mod, localnet/poktrolld/config/client.toml
This pull request includes a chore to fix bugs. The patch makes changes to various files to address the bugs, such as updating the configuration file and fixing some YAML syntax errors. Additionally, the patch updates the Go module dependencies.
- #{ISSUE_NUMBER}
[Explain the reasoning for the PR in 1-2 sentences. Consider adding a link or a screenshot.]
=> chore: fix bugs

pkg/deps/config/config.go, pkg/relayer/cmd/cmd.go
- Updates and fixes typos in godoc comments
- Removes unused code
- #126
- #177 
=> [Relayminer] chore: cleanup after 177

.github/workflows/main-build.yml, .github/workflows/run-tests.yml
Ignite upgrade seemed to break our CI, so let's downgrade first and figure out why after we merge a fix
This pull request contains multiple patches that update the main-build.yml and run-tests.yml files. The changes include upgrading the Ignite version, fixing issues with CI pipelines, and updating the installation steps.
=> [CI] Pin ignite version to 0.27.2

go.mod, go.sum, pkg/client/supplier/client_test.go, pkg/relayer/interface.go, pkg/relayer/session/sessiontree.go
- This PR updates the necessary parts of the codebase to use the latest version of the SMT
- Updated the dependency "github.com/pokt-network/smt" from version 0.7.1 to version 0.8.1.
- Added a new dependency "github.com/pokt-network/smt/kvstore/badger" with version 0.0.0-20240104123447-abb5c71c14ce.
- Modified the file "pkg/client/supplier/client_test.go" by importing the new dependencies and updating the code accordingly.
- Updated the code comments in the files "pkg/relayer/interface.go" and "pkg/relayer/session/sessiontree.go" to reflect that the SMST (Sparse Merkle State Tree) has been renamed to SMST (Sparse Merkle State Trie).
Please review these changes to ensure they are correct.
N/A
=> [SMT] Update to use v0.8.2

.gitignore, docs/static/openapi.yml, docusaurus/docs/infrastructure/localnet.md, go.mod, pkg/observable/logging/logging.go, pkg/relayer/session/claim.go
- Flush the `polylog` context when an observable is logging error
- Improve documentation for using `helm-charts` locally
- x ] **Run all unit tests**: `make go_develop_and_test`
=> [Bug] Fix observable error logging

.github/workflows/upload-pages-artifact.yml
Replace `docusaurus/package-lock.json` with `docusaurus/yarn.lock`
=> Fix upload-pages-artifact.yml

pkg/appgateserver/error_reply.go
=> [Bug] Update error_reply.go

Makefile
=> [CI] Fix CI

Makefile
Use GNU grep and sed on macos. Install if missing.
=> [Makefile] Check if gnu grep and sed needs to be installed on MacOS

pkg/crypto/rings/client.go
Refactors the `RingClient` implementation to use the new `PubKeyClient` instead of duplicating `AccountQueryClient` usage.
- #413 
=> [RingClient] refactor: to use PubKeyClient 

Tiltfile, config.yml, docusaurus/docs/configs/supplier_staking_config.md, localnet/kubernetes/values-relayminer-1.yaml, localnet/kubernetes/values-relayminer-2.yaml, localnet/kubernetes/values-relayminer-3.yaml, localnet/kubernetes/values-relayminer-common.yaml, localnet/poktrolld/config/supplier1_stake_config.yaml, localnet/poktrolld/config/supplier2_stake_config.yaml, localnet/poktrolld/config/supplier3_stake_config.yaml
Allows to scale actors on LocalNet. 
We need to be able to have multiple actors of each kind staked and in working condition on LocalNet for load-testing development.
- #20
=> [LocalNet] Allow to scale up actors

.github/workflows/upload-pages-artifact.yml, docusaurus/docs/developer_guide/quickstart.md
There's a bad link preventing from deploying docusaurus on main branch. Also, adds CI to catch such scenarios in the future.
=> [Docs] Fix docs and adjust CI to catch bad links

.github/pull_request_template.md
Update the PR template testing instructions with more explicit details
=> Update test instructions pull_request_template.md

localnet/grafana-dashboards/application_logs.json, localnet/grafana-dashboards/cometbft.json
Add `Application` logs
* `StakeApplication`
* `UnstakeApplication`
* `DelegateToGateway`
* `UndelegateFromGateway`
- [MVT Features table](https://www.notion.so/buildwithgrove/Minimum-Viable-Testnet-Success-Criteria-baa2392d0c934f408a277c6afa1b226c)
=> [Tooling] Add application stake/unstake/delegate logs

localnet/kubernetes/values-appgateserver.yaml, localnet/kubernetes/values-gateway.yaml, localnet/kubernetes/values-relayminer-common.yaml
=> [LocalNet][Hotfix] Turn off pproff by default

Makefile, localnet/grafana-dashboards/cometbft.json, localnet/grafana-dashboards/gateway_logs.json
Add Gateway logs
* StakeGateway
* UnstakeGateway
http://localhost:3003/d/gateway_logs/protocol-gateway-logs?orgId=1
- #460 
=> [Tooling] Add gateway stake/unstake/ logs

.github/workflows-helpers/run-e2e-test-job-template.yaml, .github/workflows-helpers/run-e2e-test.sh, .github/workflows/main-build.yml
Addresses an ongoing with the E2E tests:
- Modifies the RPC port of the validator;
- Adds more logging for easier troubleshooting if new issues arise in future;
=> [E2E] Add logging output from the init-container step

go.mod, go.sum, pkg/appgateserver/endpoint_selector.go, pkg/appgateserver/sdkadapter/sdk.go
Update `shannon-sdk` dependency.
Update `shannon-sdk` dependency to use the actual `main`.
=> [SDK] Use shannon sdk main branch

.github/workflows/run-tests.yml
Adds a stable marshaler gate on CI.
- #761
- #770
=> [Small PR][CI] Add check for stable marshalers

README.md, docusaurus/docs/README.md
1. Removes unnecessary front-matter section from the GitHub README.md.
2. Updates all badges to reference [pokt-network/poktroll](https://github.com/pokt-network/poktroll) instead of [pokt-network/pocket](https://github.com/pokt-network/pocket).
3. Updates the go version badge to 1.23.
See the "before" section above.
=> [Docs] Update README(s)

docusaurus/docs/operate/run_a_node/full_node_cosmovisor.md, tools/installer/full-node.sh
Use new links introduced in https://github.com/pokt-network/pocket-network-genesis/pull/7
=> [quick-pr] change full-node.sh script links

docusaurus/docusaurus.config.js, docusaurus/package-lock.json, docusaurus/package.json, docusaurus/yarn.lock
Add support for `diff` syntax highlighting in docusaurus
Context: https://github.com/pokt-network/poktroll/pull/839#issuecomment-2488620602
- #839
=> [Docs] Add support for `diff` syntax highlighting in docusaurus

docusaurus/docs/explore/rpc.md, docusaurus/docs/explore/tools.md
Update links to RPC endpoints, faucet & explorers
=> [Docs] Update links to RPC & explorers

docusaurus/docs/operate/upgrades/release_process.md, docusaurus/docs/tools/user_guide/poktrolld_cli.md
- Included [homebrew-poktroll tap](https://github.com/pokt-network/homebrew-poktroll) updates in the release process
- Update CLI documentation with troubleshooting instructions for upgrades
=> [Docs] Update release process to include homebrew tap formula

docusaurus/docs/tools/user_guide/poktrolld_cli.md
Reorganize poktrolld CLI installation docs for better readability.
=> [Docs] simplify poktrolld install doc

authorizations/grove_authorizations.json, authorizations/pnf_authorizations.json, config_mainnet.yml, docusaurus/docs/operate/morse_migration/claiming.md
- Fill in the `config_mainnet` authorization addresses in preparation for mainnet
=> [MainNet] Update `config_mainnet` authorization address

authorizations/README.md, authorizations/grove_authorizations.json, authorizations/pnf_authorizations.json, docusaurus/docs/operate/cheat_sheets/docker_compose_debian_cheatsheet.md, docusaurus/docs/operate/morse_migration/roadmap.md, docusaurus/docs/operate/upgrades/upgrade_list.md, docusaurus/docs/tools/endpoints/shannon_rpc.md, docusaurus/docs/tools/tools/shannon_alpha.md, docusaurus/docs/tools/tools/shannon_beta.md, docusaurus/docs/tools/tools/shannon_mainnet.md, docusaurus/docs/tools/tools/source_code.md, tools/installer/full-node.sh
Configuration & documentation updates during the preparation for Shannon's Shadow MainNet launch.
See [Notion Doc Diary here](https://www.notion.so/buildwithgrove/MainNet-Migration-Diary-1bfa36edfff680ccad5cd115d588d01d?pvs=4).
=> [MainNet] Shannon Shadow MainNet - Doc Updates

tools/scripts/upgrades/prepare_upgrade_tx.sh
Add upgrade transaction preparation script for automating release deployments
- Create `prepare_upgrade_tx.sh` script to automate upgrade transaction generation
- Implement checksum verification for binary downloads using `release_checksum` file
- Support multiple environments (alpha, beta, local, main) with appropriate authority addresses
- Add JSON template for Cosmos SDK upgrade messages
- Include error handling for missing parameters and failed downloads
=> [Upgrade][Migration] Added `tools/scripts/upgrades/prepare_upgrade_tx.sh`

tools/scripts/upgrades/prepare_upgrade_tx.sh, tools/scripts/upgrades/upgrade_tx_v0.1.2_alpha.json
https://github.com/pokt-network/poktroll/pull/1204/files#r2045636235
=> [QuickPR] skip checksum in upgrade TXs

app/upgrades.go, app/upgrades/v0.1.3.go
https://github.com/pokt-network/poktroll/compare/v0.1.2..b2d023a
=> [Upgrade] `v0.1.3` Upgrade Handler

docusaurus/docs/operate/upgrades/1_protocol_upgrades.md, docusaurus/docs/operate/upgrades/2_release_procedure.md
Additional documentation improvements while upgrading alpha & beta testnet to `v0.1.2` and `v0.1.3`.
=> Documentation updates during v0.1.2 and v0.1.3

docusaurus/docs/tools/user_guide/pocketd_cli.md, scripts/install.sh
Add cross-platform installation script and update documentation to simplify `pocketd` setup.
- Added `install.sh` script for easy cross-platform installation of `pocketd`
- Updated documentation to emphasize install script and include Linux instructions
- Restructured installation docs for better clarity and flow
=> chore: add install.sh script and update docs

tools/scripts/upgrades/upgrade_tx_v0.1.4_alpha.json, tools/scripts/upgrades/upgrade_tx_v0.1.4_beta.json, tools/scripts/upgrades/upgrade_tx_v0.1.4_local.json, tools/scripts/upgrades/upgrade_tx_v0.1.4_main.json
Ran this command: `"./tools/scripts/upgrades/prepare_upgrade_tx.sh v0.1.4"`
=> [Upgrade] Transactions for `v0.1.4`

app/upgrades.go, app/upgrades/v0.1.5.go, docusaurus/docs/operate/upgrades/3_testing_upgrades_locally.md
This PR adds the v0.1.5 upgrade, which aims to reduce the memory footprint when iterating over Suppliers and Applications.
* Added a new upgrade handler for v0.1.5
* Added the v0.1.5 upgrade to the allUpgrades list
* Updated documentation paths from poktroll to pocket in the local upgrade testing guide
=> [Upgrades] v0.1.5 upgrade handler to reduce memory footprint for Suppliers & Application iteration

Tiltfile
Ensure local helm charts are built when localnet is configured to use them.
=> [Tiltfile] Make sure local helm charts are built

docusaurus/docs/operate/upgrades/4_upgrade_list.md
Update upgrade list/table in the docs.
N/A
=> [Docs] Update upgrade list

docusaurus/docs/operate/morse_migration/6_claiming_account.md
Tweaking some docs for the migration process to provide clarity. Fixed broken commands.
- Updates to docs
=> [MIGRATION][DOCS] Account Migration Docs Fixes

tests/integration/migration/morse_recover_account_test.go, testutil/testmigration/fixtures_recoverable_account.go
Refactoring the migration test fixtures to provide better organization and encapsulation of test data
- Create a generic `actorFixture` type to store actors, their claimable accounts, and private keys together
- Improve data organization with new `actorTypeGroups` structure to group fixtures by their types
- Add getter methods for accessing fixture data for different actor types
- Remove manual tracking of addresses in `recoverableAddressesByActorType` in favor of structured fixtures
- Simplify the `initMigrationFixtures` function to return the entire fixtures object
- Adjust test cases to use the new fixture accessor methods
=> [Migration] Refactor Morse migration test fixtures for better organization and easier test data access

docusaurus/docs/1_operate/4_faq/2_full_node_faq.md
Expand full node FAQ with upgrade checks, releases info, and Beta TestNet details
- Add section on checking for applied upgrades using `pocketd query upgrade`
- Add information about protocol upgrades and release tracking resources
- Include details about Beta TestNet early block validation issues and workarounds
- Add guidance on RPC endpoint usage (public vs. self-hosted)
- Add links to deployment solutions and Cosmovisor setup
=> [Documentation] Update Full Node FAQ with details shared to community

app/upgrades.go, app/upgrades/v0.1.12.go
=> [Upgrade] v0.1.12

.github/workflows/main-build.yml, tests/integration/migration/morse_claim_app_test.go, tests/integration/migration/morse_claim_supplier_test.go, testutil/integration/app.go, x/migration/keeper/msg_server_claim_morse_application.go, x/migration/keeper/msg_server_claim_morse_supplier.go, x/migration/types/morse_claimable_account.go
go test -v -count=1  ./tests/integration/... --tags=test
=> Review of #1338

docusaurus/docs/2_explore/1_tools/2_shannon_beta.md
- Add Beta TestNet MACT faucet link
- Update BetaTestNet POKT faucet link (skips token selection)
- N/A
=> [Docs] Add Beta TestNet MACT faucet link

go.mod, go.sum
https://github.com/pokt-network/shannon-sdk/pull/36
```bash
go get github.com/pokt-network/shannon-sdk
go mod tidy
```
=> [Deps] Update Shannon SDK

tools/scripts/params/bulk_params/tokenomics_params.json, tools/scripts/params/bulk_params_main/gateway_params.json, tools/scripts/params/bulk_params_main/proof_params.json, tools/scripts/params/bulk_params_main/service_params.json, tools/scripts/params/bulk_params_main/shared_params.json, tools/scripts/params/bulk_params_main/tokenomics_params.json, tools/scripts/params/update_all_params.sh
> [!IMPORTANT]
> To query all params on main, run: `./tools/scripts/params/gov_params.sh query-all --env main`
> The values in github ARE NOT the source of truth. Onchain is.
---
- Update `tools/scripts/params/bulk_params/tokenomics_params.json
- Update `tools/scripts/params/update_all_params.sh`
- Supersedes #1412
=> [Governance] Update MainNet Bulk Params

tools/scripts/migration/README.md
- Morse -> Shannon MainNet State Migration artifacts
- Instructions can be found here: https://dev.poktroll.com/explore/morse_migration/state_transfer_playbook
```bash
pocketd query \
--node=https://shannon-grove-rpc.mainnet.poktroll.com tx \
--type=hash  E4E74523CAC90E021AD181DBD1C6569AB0FD53FFBA2C4C639C963918F80869B3 \
>> /tmp/E4E74523CAC90E021AD181DBD1C6569AB0FD53FFBA2C4C639C963918F80869B3.txt
```
```bash
pocketd query migration show-morse-claimable-account c409a9e0d1be8780fe0b29dcdf72f8a879fb110c --node=https://shannon-grove-rpc.mainnet.poktroll.com
```
```yaml
morseClaimableAccount:
application_stake:
amount: "0"
denom: upokt
morse_output_address: B05BC83D16B8F682630B5A14F0D06C9073523932
morse_src_address: C409A9E0D1BE8780FE0B29DCDF72F8A879FB110C
supplier_stake:
amount: "0"
denom: …
```
=> [Migration] Morse -> Shannon MainNet State Migration Artifacts

app/upgrades.go, app/upgrades/v0.1.17.go
Implement the 0.1.17 upgrade handler
=> [Upgrade] Implement the 0.1.17 upgrade handler

pkg/client/events/replay_client.go, pkg/client/tx/context.go, pkg/relayer/session/claim.go, pkg/relayer/session/persistence.go, pkg/relayer/session/proof.go, pkg/relayer/session/session.go, pkg/relayer/session/sessiontree.go
Reverts pokt-network/poktroll#1480
=> Revert "[RelayMiner] Improve Context Handling and Session Tree Management in Relayer"

app/upgrades.go, app/upgrades/v0.1.20.go, app/upgrades/vNEXT.go
[Upgrade] V0.1.20 Upgrade Handler
=> [Upgrade] V0.1.20 Upgrade Handler

tools/scripts/upgrades/upgrade_tx_v0.1.20_alpha.json, tools/scripts/upgrades/upgrade_tx_v0.1.20_beta.json, tools/scripts/upgrades/upgrade_tx_v0.1.20_local.json, tools/scripts/upgrades/upgrade_tx_v0.1.20_main.json
```bash
export RPC_ENDPOINT=https://shannon-testnet-grove-rpc.alpha.poktroll.com
export UPGRADE_TX_JSON="tools/scripts/upgrades/upgrade_tx_v0.1.20_alpha.json"
export NETWORK=alpha
export FROM_ACCOUNT=pnf_alpha
```
```bash
CURRENT_HEIGHT=$(pocketd q block --network=${NETWORK} -o json | tail -n +2 | jq -r '.header.height') # Add 5 blocks (arbitrary, adjust as needed)
UPGRADE_HEIGHT=$((CURRENT_HEIGHT + 3))
sed -i.bak "s/\"height\": \"[^\"]*\"/\"height\": \"$UPGRADE_HEIGHT\"/" ${UPGRADE_TX_JSON}
cat ${UPGRADE_TX_JSON}
```
```bash
pocketd \
--keyring-backend="test" --home="~/.pocket_prod" \
--fees=300upokt --network=${NETWORK} \
tx authz exec ${UPGRADE_TX_JSON} --from=${FROM_ACCOUNT}
```
```bash
watch -n 5 "pocketd query upgrade plan --network=alpha"
watch -n 5 "curl -s …
```
=> v0.1.20 release transactions

tools/scripts/params/bulk_params_beta/supplier_params.json, tools/scripts/params/bulk_params_main/supplier_params.json
```bash
ppcketd tx authz exec ./supplier_params_beta_20250616_115321.json --from=pokt1f0c9y7mahf2ya8tymy8g4rr75ezh3pkklu4c3e --keyring-backend=test --chain-id=pocket-beta --node=https://shannon-testnet-grove-rpc.beta.poktroll.com --yes --home=/Users/olshansky/.pocket_prod --fees=200upokt
```
```bash
EEBD97F9B78FDEE03363B84E0043FAE6069D561731485BA3123736B6E40634C5
```
```bash
pocketd tx authz exec ./supplier_params_main_20250616_115246.json --from=pokt18808wvw0h4t450t06uvauny8lvscsxjfyua7vh --keyring-backend=test --chain-id=pocket --node=https://shannon-grove-rpc.mainnet.poktroll.com --yes --home=/Users/olshansky/.pocket_prod --fees=200upokt
```
Hash
```bash
59FC3746ADAB988F64E301E8F10C247DDB12D1AAF165B2E30F0082CDC39AE8FE
```
=> [Migration] Set supplier params to 0

tools/scripts/params/bulk_params_beta/supplier_params.json, tools/scripts/params/bulk_params_main/supplier_params.json
Reverts pokt-network/poktroll#1501
=> Revert "[Migration] Set supplier params to 0"

app/upgrades.go, app/upgrades/v0.1.22.go
Onchain upgrade v0.1.22 
- #1542 
- #1543
- #1549 
- #1550
=> [Upgrade] v0.1.22

.github/workflows/notify-telegram-groups.yml
- Fix the manual dispatch of the release bot
=> [Telegram Bot] Release Telegram Bot - Fix manual dispatch

Makefile, docusaurus/docs/2_explore/2_account_management/1_pocketd_cli.md, docusaurus/docs/4_develop/upgrades/2_release_procedure.md, makefiles/colors.mk, makefiles/release.mk
- Added `makefiles/colors.mk` to make makefile outputs easier to follow
- Added `make release_tag_dev` to publish releases from a branch
- Refactored and cleanup all other release related makefile targets
=> [Makefile] Improved and refactored release tags

pkg/relayer/session/claim.go, pkg/relayer/session/proof.go
[Session Rollover] Separating C&P
=> [Session Rollover] Separating C&P

docusaurus/docs/4_develop/upgrades/2_release_procedure.md, x/tokenomics/keeper/token_logic_modules_test.go, x/tokenomics/token_logic_module/distribution.go, x/tokenomics/token_logic_module/distribution_sorting.go, x/tokenomics/token_logic_module/distribution_supplier.go, x/tokenomics/token_logic_module/distribution_validator.go, x/tokenomics/token_logic_module/settlement_results.go, x/tokenomics/token_logic_module/tlm_global_mint.go, x/tokenomics/token_logic_module/tlm_relay_burn_equals_mint.go, x/tokenomics/token_logic_module/validator_distribution_determinism_test.go
Fix non-deterministic iteration in validator/delegator reward distribution.
- N/A
=> [Bug] fix: non-deterministic onchain iteration

docusaurus/docs/4_develop/upgrades/3_mainnet_release_procedure.md, tools/scripts/upgrades/cancel_upgrade_alpha.json, tools/scripts/upgrades/cancel_upgrade_beta.json, tools/scripts/upgrades/cancel_upgrade_main.json, tools/scripts/upgrades/submit_upgrade.sh, tools/scripts/upgrades/upgrade_tx_v0.1.29_main.json
Docs & tooling to cancel upgrades.
=> [Docs] Cancelling upgrades
